//-----------------------------------------------------------------------
// <copyright file=" cgform_template.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_template.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_template Entity Model
    /// </summary>    
    [Table("cgform_template")]
    public class cgform_template : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _template_name;
        /// <summary>
        /// 模板名称
        /// </summary>
        public string template_name
        {
            get { return _template_name; }
            set { updateProper(ref _template_name, value);}
        }
    
        private string _template_code;
        /// <summary>
        /// 模板编码
        /// </summary>
        public string template_code
        {
            get { return _template_code; }
            set { updateProper(ref _template_code, value);}
        }
    
        private string _template_type;
        /// <summary>
        /// 模板类型
        /// </summary>
        public string template_type
        {
            get { return _template_type; }
            set { updateProper(ref _template_type, value);}
        }
    
        private string _template_share;
        /// <summary>
        /// 是否共享
        /// </summary>
        public string template_share
        {
            get { return _template_share; }
            set { updateProper(ref _template_share, value);}
        }
    
        private string _template_pic;
        /// <summary>
        /// 预览图
        /// </summary>
        public string template_pic
        {
            get { return _template_pic; }
            set { updateProper(ref _template_pic, value);}
        }
    
        private string _template_comment;
        /// <summary>
        /// 模板描述
        /// </summary>
        public string template_comment
        {
            get { return _template_comment; }
            set { updateProper(ref _template_comment, value);}
        }
    
        private string _template_list_name;
        /// <summary>
        /// 列表模板名称

        /// </summary>
        public string template_list_name
        {
            get { return _template_list_name; }
            set { updateProper(ref _template_list_name, value);}
        }
    
        private string _template_add_name;
        /// <summary>
        /// 录入模板名称
        /// </summary>
        public string template_add_name
        {
            get { return _template_add_name; }
            set { updateProper(ref _template_add_name, value);}
        }
    
        private string _template_update_name;
        /// <summary>
        /// 编辑模板名
称
        /// </summary>
        public string template_update_name
        {
            get { return _template_update_name; }
            set { updateProper(ref _template_update_name, value);}
        }
    
        private string _template_detail_name;
        /// <summary>
        /// 查看页面模
板名称
        /// </summary>
        public string template_detail_name
        {
            get { return _template_detail_name; }
            set { updateProper(ref _template_detail_name, value);}
        }
    
        private int? _status;
        /// <summary>
        /// 有效状态
        /// </summary>
        public int? status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    }
}
