//-----------------------------------------------------------------------
// <copyright file=" cgform_enhance_js.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_enhance_js.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// cgform_enhance_js Entity Model
    /// </summary>    
    [Table("cgform_enhance_js")]
    public class cgform_enhance_js
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// JS增强内容
        /// </summary>
        public string CG_JS { get; set; }
    
        /// <summary>
        /// 类型
        /// </summary>
        public string CG_JS_TYPE { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string CONTENT { get; set; }
    
        /// <summary>
        /// 表单ID
        /// </summary>
        public string FORM_ID { get; set; }
    }
}
