//-----------------------------------------------------------------------
// <copyright file=" cgform_ftl.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_ftl.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_ftl Entity Model
    /// </summary>    
    [Table("cgform_ftl")]
    public class cgform_ftl : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _CGFORM_ID;
        /// <summary>
        /// 表单ID
        /// </summary>
        public string CGFORM_ID
        {
            get { return _CGFORM_ID; }
            set { updateProper(ref _CGFORM_ID, value);}
        }
    
        private string _CGFORM_NAME;
        /// <summary>
        /// 表单名字
        /// </summary>
        public string CGFORM_NAME
        {
            get { return _CGFORM_NAME; }
            set { updateProper(ref _CGFORM_NAME, value);}
        }
    
        private string _CREATE_BY;
        /// <summary>
        /// 创建人
        /// </summary>
        public string CREATE_BY
        {
            get { return _CREATE_BY; }
            set { updateProper(ref _CREATE_BY, value);}
        }
    
        private DateTime? _CREATE_DATE;
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? CREATE_DATE
        {
            get { return _CREATE_DATE; }
            set { updateProper(ref _CREATE_DATE, value);}
        }
    
        private string _CREATE_NAME;
        /// <summary>
        /// 创建人名字
        /// </summary>
        public string CREATE_NAME
        {
            get { return _CREATE_NAME; }
            set { updateProper(ref _CREATE_NAME, value);}
        }
    
        private string _FTL_CONTENT;
        /// <summary>
        /// 设计模板内容
        /// </summary>
        public string FTL_CONTENT
        {
            get { return _FTL_CONTENT; }
            set { updateProper(ref _FTL_CONTENT, value);}
        }
    
        private string _FTL_STATUS;
        /// <summary>
        /// 模板激活状态
        /// </summary>
        public string FTL_STATUS
        {
            get { return _FTL_STATUS; }
            set { updateProper(ref _FTL_STATUS, value);}
        }
    
        private int? _FTL_VERSION;
        /// <summary>
        /// 模板编号
        /// </summary>
        public int? FTL_VERSION
        {
            get { return _FTL_VERSION; }
            set { updateProper(ref _FTL_VERSION, value);}
        }
    
        private string _FTL_WORD_URL;
        /// <summary>
        /// 上传Word路径
        /// </summary>
        public string FTL_WORD_URL
        {
            get { return _FTL_WORD_URL; }
            set { updateProper(ref _FTL_WORD_URL, value);}
        }
    
        private string _UPDATE_BY;
        /// <summary>
        /// 修改人
        /// </summary>
        public string UPDATE_BY
        {
            get { return _UPDATE_BY; }
            set { updateProper(ref _UPDATE_BY, value);}
        }
    
        private DateTime? _UPDATE_DATE;
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? UPDATE_DATE
        {
            get { return _UPDATE_DATE; }
            set { updateProper(ref _UPDATE_DATE, value);}
        }
    
        private string _UPDATE_NAME;
        /// <summary>
        /// 修改人名字
        /// </summary>
        public string UPDATE_NAME
        {
            get { return _UPDATE_NAME; }
            set { updateProper(ref _UPDATE_NAME, value);}
        }
    
        private string _editor_type;
        /// <summary>
        /// 类型
        /// </summary>
        public string editor_type
        {
            get { return _editor_type; }
            set { updateProper(ref _editor_type, value);}
        }
    }
}
