//-----------------------------------------------------------------------
// <copyright file=" cgform_enhance_java.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_enhance_java.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// cgform_enhance_java Entity Model
    /// </summary>    
export class cgform_enhance_java
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 按钮编码
        /// </summary>
    public button_code:string;
    
        /// <summary>
        /// 类型
        /// </summary>
    public cg_java_type:string;
    
        /// <summary>
        /// 数值
        /// </summary>
    public cg_java_value:string;
    
        /// <summary>
        /// 表单ID
        /// </summary>
    public form_id:string;
    
        /// <summary>
        /// 生效状态
        /// </summary>
    public active_status:string;
}

