//-----------------------------------------------------------------------
// <copyright file=" cgform_field.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_field.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// cgform_field Entity Model
    /// </summary>    
    [Table("cgform_field")]
    public class cgform_field
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 字段备注
        /// </summary>
        public string content { get; set; }
    
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 创建人名字
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 字典code
        /// </summary>
        public string dict_field { get; set; }
    
        /// <summary>
        /// 字典表
        /// </summary>
        public string dict_table { get; set; }
    
        /// <summary>
        /// 字典Text
        /// </summary>
        public string dict_text { get; set; }
    
        /// <summary>
        /// 表字段默认值
        /// </summary>
        public string field_default { get; set; }
    
        /// <summary>
        /// 跳转URL
        /// </summary>
        public string field_href { get; set; }
    
        /// <summary>
        /// 表单控件长度
        /// </summary>
        public int? field_length { get; set; }
    
        /// <summary>
        /// 字段名字
        /// </summary>
        public string field_name { get; set; }
    
        /// <summary>
        /// 表单字段校验规则
        /// </summary>
        public string field_valid_type { get; set; }
    
        /// <summary>
        /// 字段是否必填
        /// </summary>
        public string field_must_input { get; set; }
    
        /// <summary>
        /// 是否主键
        /// </summary>
        public string is_key { get; set; }
    
        /// <summary>
        /// 是否允许为空
        /// </summary>
        public string is_null { get; set; }
    
        /// <summary>
        /// 是否查询条件
        /// </summary>
        public string is_query { get; set; }
    
        /// <summary>
        /// 表单是否显示
        /// </summary>
        public string is_show { get; set; }
    
        /// <summary>
        /// 列表是否显示
        /// </summary>
        public string is_show_list { get; set; }
    
        /// <summary>
        /// 数据库字段长度
        /// </summary>
        public int? length { get; set; }
    
        /// <summary>
        /// 外键主键字段
        /// </summary>
        public string main_field { get; set; }
    
        /// <summary>
        /// 外键主表名
        /// </summary>
        public string main_table { get; set; }
    
        /// <summary>
        /// 原字段名
        /// </summary>
        public string old_field_name { get; set; }
    
        /// <summary>
        /// 原排列序号
        /// </summary>
        public int? order_num { get; set; }
    
        /// <summary>
        /// 小数点
        /// </summary>
        public int? point_length { get; set; }
    
        /// <summary>
        /// 查询模式
        /// </summary>
        public string query_mode { get; set; }
    
        /// <summary>
        /// 表单控件类型
        /// </summary>
        public string show_type { get; set; }
    
        /// <summary>
        /// 数据库字段类型
        /// </summary>
        public string type { get; set; }
    
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 修改人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 表ID
        /// </summary>
        public string table_id { get; set; }
    
        /// <summary>
        /// 扩展参数JSON
        /// </summary>
        public string extend_json { get; set; }
    }
}
