//-----------------------------------------------------------------------
// <copyright file=" cgform_button_sql.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_button_sql.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_button_sql Entity Model
    /// </summary>    
    [Table("cgform_button_sql")]
    public class cgform_button_sql : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _BUTTON_CODE;
        /// <summary>
        /// 按钮编码
        /// </summary>
        public string BUTTON_CODE
        {
            get { return _BUTTON_CODE; }
            set { updateProper(ref _BUTTON_CODE, value);}
        }
    
        private string _CGB_SQL;
        /// <summary>
        /// SQL内容
        /// </summary>
        public string CGB_SQL
        {
            get { return _CGB_SQL; }
            set { updateProper(ref _CGB_SQL, value);}
        }
    
        private string _CGB_SQL_NAME;
        /// <summary>
        /// Sql名称
        /// </summary>
        public string CGB_SQL_NAME
        {
            get { return _CGB_SQL_NAME; }
            set { updateProper(ref _CGB_SQL_NAME, value);}
        }
    
        private string _CONTENT;
        /// <summary>
        /// 备注
        /// </summary>
        public string CONTENT
        {
            get { return _CONTENT; }
            set { updateProper(ref _CONTENT, value);}
        }
    
        private string _FORM_ID;
        /// <summary>
        /// 表单ID
        /// </summary>
        public string FORM_ID
        {
            get { return _FORM_ID; }
            set { updateProper(ref _FORM_ID, value);}
        }
    }
}
