//-----------------------------------------------------------------------
// <copyright file=" cgform_template.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_template.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// cgform_template Entity Model
    /// </summary>    
export class cgform_template
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 模板名称
        /// </summary>
    public template_name:string;
    
        /// <summary>
        /// 模板编码
        /// </summary>
    public template_code:string;
    
        /// <summary>
        /// 模板类型
        /// </summary>
    public template_type:string;
    
        /// <summary>
        /// 是否共享
        /// </summary>
    public template_share:string;
    
        /// <summary>
        /// 预览图
        /// </summary>
    public template_pic:string;
    
        /// <summary>
        /// 模板描述
        /// </summary>
    public template_comment:string;
    
        /// <summary>
        /// 列表模板名称

        /// </summary>
    public template_list_name:string;
    
        /// <summary>
        /// 录入模板名称
        /// </summary>
    public template_add_name:string;
    
        /// <summary>
        /// 编辑模板名
称
        /// </summary>
    public template_update_name:string;
    
        /// <summary>
        /// 查看页面模
板名称
        /// </summary>
    public template_detail_name:string;
    
        /// <summary>
        /// 有效状态
        /// </summary>
    public status:number;
}

