//-----------------------------------------------------------------------
// <copyright file=" cgform_enhance_js.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_enhance_js.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// cgform_enhance_js Entity Model
    /// </summary>    
export class cgform_enhance_js
{
        /// <summary>
        /// 主键ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// JS增强内容
        /// </summary>
    public CG_JS:string;
    
        /// <summary>
        /// 类型
        /// </summary>
    public CG_JS_TYPE:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public CONTENT:string;
    
        /// <summary>
        /// 表单ID
        /// </summary>
    public FORM_ID:string;
}

