//-----------------------------------------------------------------------
// <copyright file=" cgform_button_sql.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_button_sql.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// cgform_button_sql Entity Model
    /// </summary>    
export class cgform_button_sql
{
        /// <summary>
        /// 主键ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 按钮编码
        /// </summary>
    public BUTTON_CODE:string;
    
        /// <summary>
        /// SQL内容
        /// </summary>
    public CGB_SQL:string;
    
        /// <summary>
        /// Sql名称
        /// </summary>
    public CGB_SQL_NAME:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public CONTENT:string;
    
        /// <summary>
        /// 表单ID
        /// </summary>
    public FORM_ID:string;
}

