//-----------------------------------------------------------------------
// <copyright file=" cgform_field.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_field.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_field Entity Model
    /// </summary>    
    [Table("cgform_field")]
    public class cgform_field : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _content;
        /// <summary>
        /// 字段备注
        /// </summary>
        public string content
        {
            get { return _content; }
            set { updateProper(ref _content, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名字
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _dict_field;
        /// <summary>
        /// 字典code
        /// </summary>
        public string dict_field
        {
            get { return _dict_field; }
            set { updateProper(ref _dict_field, value);}
        }
    
        private string _dict_table;
        /// <summary>
        /// 字典表
        /// </summary>
        public string dict_table
        {
            get { return _dict_table; }
            set { updateProper(ref _dict_table, value);}
        }
    
        private string _dict_text;
        /// <summary>
        /// 字典Text
        /// </summary>
        public string dict_text
        {
            get { return _dict_text; }
            set { updateProper(ref _dict_text, value);}
        }
    
        private string _field_default;
        /// <summary>
        /// 表字段默认值
        /// </summary>
        public string field_default
        {
            get { return _field_default; }
            set { updateProper(ref _field_default, value);}
        }
    
        private string _field_href;
        /// <summary>
        /// 跳转URL
        /// </summary>
        public string field_href
        {
            get { return _field_href; }
            set { updateProper(ref _field_href, value);}
        }
    
        private int? _field_length;
        /// <summary>
        /// 表单控件长度
        /// </summary>
        public int? field_length
        {
            get { return _field_length; }
            set { updateProper(ref _field_length, value);}
        }
    
        private string _field_name;
        /// <summary>
        /// 字段名字
        /// </summary>
        public string field_name
        {
            get { return _field_name; }
            set { updateProper(ref _field_name, value);}
        }
    
        private string _field_valid_type;
        /// <summary>
        /// 表单字段校验规则
        /// </summary>
        public string field_valid_type
        {
            get { return _field_valid_type; }
            set { updateProper(ref _field_valid_type, value);}
        }
    
        private string _field_must_input;
        /// <summary>
        /// 字段是否必填
        /// </summary>
        public string field_must_input
        {
            get { return _field_must_input; }
            set { updateProper(ref _field_must_input, value);}
        }
    
        private string _is_key;
        /// <summary>
        /// 是否主键
        /// </summary>
        public string is_key
        {
            get { return _is_key; }
            set { updateProper(ref _is_key, value);}
        }
    
        private string _is_null;
        /// <summary>
        /// 是否允许为空
        /// </summary>
        public string is_null
        {
            get { return _is_null; }
            set { updateProper(ref _is_null, value);}
        }
    
        private string _is_query;
        /// <summary>
        /// 是否查询条件
        /// </summary>
        public string is_query
        {
            get { return _is_query; }
            set { updateProper(ref _is_query, value);}
        }
    
        private string _is_show;
        /// <summary>
        /// 表单是否显示
        /// </summary>
        public string is_show
        {
            get { return _is_show; }
            set { updateProper(ref _is_show, value);}
        }
    
        private string _is_show_list;
        /// <summary>
        /// 列表是否显示
        /// </summary>
        public string is_show_list
        {
            get { return _is_show_list; }
            set { updateProper(ref _is_show_list, value);}
        }
    
        private int? _length;
        /// <summary>
        /// 数据库字段长度
        /// </summary>
        public int? length
        {
            get { return _length; }
            set { updateProper(ref _length, value);}
        }
    
        private string _main_field;
        /// <summary>
        /// 外键主键字段
        /// </summary>
        public string main_field
        {
            get { return _main_field; }
            set { updateProper(ref _main_field, value);}
        }
    
        private string _main_table;
        /// <summary>
        /// 外键主表名
        /// </summary>
        public string main_table
        {
            get { return _main_table; }
            set { updateProper(ref _main_table, value);}
        }
    
        private string _old_field_name;
        /// <summary>
        /// 原字段名
        /// </summary>
        public string old_field_name
        {
            get { return _old_field_name; }
            set { updateProper(ref _old_field_name, value);}
        }
    
        private int? _order_num;
        /// <summary>
        /// 原排列序号
        /// </summary>
        public int? order_num
        {
            get { return _order_num; }
            set { updateProper(ref _order_num, value);}
        }
    
        private int? _point_length;
        /// <summary>
        /// 小数点
        /// </summary>
        public int? point_length
        {
            get { return _point_length; }
            set { updateProper(ref _point_length, value);}
        }
    
        private string _query_mode;
        /// <summary>
        /// 查询模式
        /// </summary>
        public string query_mode
        {
            get { return _query_mode; }
            set { updateProper(ref _query_mode, value);}
        }
    
        private string _show_type;
        /// <summary>
        /// 表单控件类型
        /// </summary>
        public string show_type
        {
            get { return _show_type; }
            set { updateProper(ref _show_type, value);}
        }
    
        private string _type;
        /// <summary>
        /// 数据库字段类型
        /// </summary>
        public string type
        {
            get { return _type; }
            set { updateProper(ref _type, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 修改人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _table_id;
        /// <summary>
        /// 表ID
        /// </summary>
        public string table_id
        {
            get { return _table_id; }
            set { updateProper(ref _table_id, value);}
        }
    
        private string _extend_json;
        /// <summary>
        /// 扩展参数JSON
        /// </summary>
        public string extend_json
        {
            get { return _extend_json; }
            set { updateProper(ref _extend_json, value);}
        }
    }
}
