//-----------------------------------------------------------------------
// <copyright file=" cgform_index.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_index.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// cgform_index Entity Model
    /// </summary>    
    [Serializable]
    public class cgform_index
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime update_date { get; set; }
    
        /// <summary>
        /// 索引名称
        /// </summary>
        public string index_name { get; set; }
    
        /// <summary>
        /// 索引栏位
        /// </summary>
        public string index_field { get; set; }
    
        /// <summary>
        /// 索引类型
        /// </summary>
        public string index_type { get; set; }
    
        /// <summary>
        /// 主表id
        /// </summary>
        public string table_id { get; set; }
    }
}
