//-----------------------------------------------------------------------
// <copyright file=" cgform_enhance_js.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_enhance_js.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_enhance_js Entity Model
    /// </summary>    
    [Table("cgform_enhance_js")]
    public class cgform_enhance_js : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _CG_JS;
        /// <summary>
        /// JS增强内容
        /// </summary>
        public string CG_JS
        {
            get { return _CG_JS; }
            set { updateProper(ref _CG_JS, value);}
        }
    
        private string _CG_JS_TYPE;
        /// <summary>
        /// 类型
        /// </summary>
        public string CG_JS_TYPE
        {
            get { return _CG_JS_TYPE; }
            set { updateProper(ref _CG_JS_TYPE, value);}
        }
    
        private string _CONTENT;
        /// <summary>
        /// 备注
        /// </summary>
        public string CONTENT
        {
            get { return _CONTENT; }
            set { updateProper(ref _CONTENT, value);}
        }
    
        private string _FORM_ID;
        /// <summary>
        /// 表单ID
        /// </summary>
        public string FORM_ID
        {
            get { return _FORM_ID; }
            set { updateProper(ref _FORM_ID, value);}
        }
    }
}
