//-----------------------------------------------------------------------
// <copyright file=" cgform_uploadfiles.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: cgform_uploadfiles.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// cgform_uploadfiles Entity Model
    /// </summary>    
    [Table("cgform_uploadfiles")]
    public class cgform_uploadfiles : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _CGFORM_FIELD;
        /// <summary>
        /// 表单字段
        /// </summary>
        public string CGFORM_FIELD
        {
            get { return _CGFORM_FIELD; }
            set { updateProper(ref _CGFORM_FIELD, value);}
        }
    
        private string _CGFORM_ID;
        /// <summary>
        /// 表单ID
        /// </summary>
        public string CGFORM_ID
        {
            get { return _CGFORM_ID; }
            set { updateProper(ref _CGFORM_ID, value);}
        }
    
        private string _CGFORM_NAME;
        /// <summary>
        /// 表单名称
        /// </summary>
        public string CGFORM_NAME
        {
            get { return _CGFORM_NAME; }
            set { updateProper(ref _CGFORM_NAME, value);}
        }
    }
}
