//-----------------------------------------------------------------------
// <copyright file=" gk_chemicla_manage.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_chemicla_manage.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// gk_chemicla_manage Entity Model
    /// </summary>    
    [Table("gk_chemicla_manage")]
    public class gk_chemicla_manage : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _name;
        /// <summary>
        /// 姓名
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private string _sex;
        /// <summary>
        /// 性别
        /// </summary>
        public string sex
        {
            get { return _sex; }
            set { updateProper(ref _sex, value);}
        }
    
        private DateTime? _birthday;
        /// <summary>
        /// 出生日期
        /// </summary>
        public DateTime? birthday
        {
            get { return _birthday; }
            set { updateProper(ref _birthday, value);}
        }
    
        private string _politics_face;
        /// <summary>
        /// 政治面貌
        /// </summary>
        public string politics_face
        {
            get { return _politics_face; }
            set { updateProper(ref _politics_face, value);}
        }
    
        private string _nationality;
        /// <summary>
        /// 民族
        /// </summary>
        public string nationality
        {
            get { return _nationality; }
            set { updateProper(ref _nationality, value);}
        }
    
        private string _phone;
        /// <summary>
        /// 手机号码
        /// </summary>
        public string phone
        {
            get { return _phone; }
            set { updateProper(ref _phone, value);}
        }
    
        private string _fixed_phone;
        /// <summary>
        /// 固定电话
        /// </summary>
        public string fixed_phone
        {
            get { return _fixed_phone; }
            set { updateProper(ref _fixed_phone, value);}
        }
    
        private string _work_unit;
        /// <summary>
        /// 工作单位
        /// </summary>
        public string work_unit
        {
            get { return _work_unit; }
            set { updateProper(ref _work_unit, value);}
        }
    
        private string _duty;
        /// <summary>
        /// 职务
        /// </summary>
        public string duty
        {
            get { return _duty; }
            set { updateProper(ref _duty, value);}
        }
    
        private string _work_address;
        /// <summary>
        /// 办公地址
        /// </summary>
        public string work_address
        {
            get { return _work_address; }
            set { updateProper(ref _work_address, value);}
        }
    
        private string _postcode;
        /// <summary>
        /// 邮编
        /// </summary>
        public string postcode
        {
            get { return _postcode; }
            set { updateProper(ref _postcode, value);}
        }
    
        private string _certificate_type;
        /// <summary>
        /// 证件类型
        /// </summary>
        public string certificate_type
        {
            get { return _certificate_type; }
            set { updateProper(ref _certificate_type, value);}
        }
    
        private string _certificate_no;
        /// <summary>
        /// 证件号
        /// </summary>
        public string certificate_no
        {
            get { return _certificate_no; }
            set { updateProper(ref _certificate_no, value);}
        }
    
        private string _graduate_school;
        /// <summary>
        /// 毕业院校
        /// </summary>
        public string graduate_school
        {
            get { return _graduate_school; }
            set { updateProper(ref _graduate_school, value);}
        }
    
        private DateTime? _graduate_time;
        /// <summary>
        /// 毕业时间
        /// </summary>
        public DateTime? graduate_time
        {
            get { return _graduate_time; }
            set { updateProper(ref _graduate_time, value);}
        }
    
        private string _graduate_major;
        /// <summary>
        /// 专业
        /// </summary>
        public string graduate_major
        {
            get { return _graduate_major; }
            set { updateProper(ref _graduate_major, value);}
        }
    
        private string _graduate_education;
        /// <summary>
        /// 学历
        /// </summary>
        public string graduate_education
        {
            get { return _graduate_education; }
            set { updateProper(ref _graduate_education, value);}
        }
    
        private DateTime? _work_time_start;
        /// <summary>
        /// 参加工作时间
        /// </summary>
        public DateTime? work_time_start
        {
            get { return _work_time_start; }
            set { updateProper(ref _work_time_start, value);}
        }
    
        private string _work_year;
        /// <summary>
        /// 从业年限
        /// </summary>
        public string work_year
        {
            get { return _work_year; }
            set { updateProper(ref _work_year, value);}
        }
    
        private string _examine_type;
        /// <summary>
        /// 考试科目
        /// </summary>
        public string examine_type
        {
            get { return _examine_type; }
            set { updateProper(ref _examine_type, value);}
        }
    
        private DateTime? _examine_time;
        /// <summary>
        /// 考试时间
        /// </summary>
        public DateTime? examine_time
        {
            get { return _examine_time; }
            set { updateProper(ref _examine_time, value);}
        }
    
        private string _examine_center;
        /// <summary>
        /// 考试中心
        /// </summary>
        public string examine_center
        {
            get { return _examine_center; }
            set { updateProper(ref _examine_center, value);}
        }
    
        private string _examine_address;
        /// <summary>
        /// 考试地址
        /// </summary>
        public string examine_address
        {
            get { return _examine_address; }
            set { updateProper(ref _examine_address, value);}
        }
    
        private string _examine_scope;
        /// <summary>
        /// 考试分数
        /// </summary>
        public string examine_scope
        {
            get { return _examine_scope; }
            set { updateProper(ref _examine_scope, value);}
        }
    
        private string _email;
        /// <summary>
        /// 电子邮箱
        /// </summary>
        public string email
        {
            get { return _email; }
            set { updateProper(ref _email, value);}
        }
    
        private string _rewards_punish;
        /// <summary>
        /// 奖惩记录
        /// </summary>
        public string rewards_punish
        {
            get { return _rewards_punish; }
            set { updateProper(ref _rewards_punish, value);}
        }
    
        private string _work_experience;
        /// <summary>
        /// 主要工作经历描述
        /// </summary>
        public string work_experience
        {
            get { return _work_experience; }
            set { updateProper(ref _work_experience, value);}
        }
    
        private DateTime? _apply_date;
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime? apply_date
        {
            get { return _apply_date; }
            set { updateProper(ref _apply_date, value);}
        }
    
        private string _certi_number;
        /// <summary>
        /// 从业资格证书编号
        /// </summary>
        public string certi_number
        {
            get { return _certi_number; }
            set { updateProper(ref _certi_number, value);}
        }
    
        private string _certi_type;
        /// <summary>
        /// 从业资格证书类型
        /// </summary>
        public string certi_type
        {
            get { return _certi_type; }
            set { updateProper(ref _certi_type, value);}
        }
    
        private string _certi_organ;
        /// <summary>
        /// 发证机关
        /// </summary>
        public string certi_organ
        {
            get { return _certi_organ; }
            set { updateProper(ref _certi_organ, value);}
        }
    
        private DateTime? _certi_date;
        /// <summary>
        /// 发证日期
        /// </summary>
        public DateTime? certi_date
        {
            get { return _certi_date; }
            set { updateProper(ref _certi_date, value);}
        }
    
        private string _national_type;
        /// <summary>
        /// 从事国际水路运输类型
        /// </summary>
        public string national_type
        {
            get { return _national_type; }
            set { updateProper(ref _national_type, value);}
        }
    
        private string _inland_type;
        /// <summary>
        /// 从事国内水路运输类型
        /// </summary>
        public string inland_type
        {
            get { return _inland_type; }
            set { updateProper(ref _inland_type, value);}
        }
    }
}
