//-----------------------------------------------------------------------
// <copyright file=" gk_chemicla_check.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_chemicla_check.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_chemicla_check Entity Model
    /// </summary>    
export class gk_chemicla_check
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 姓名
        /// </summary>
    public name:string;
    
        /// <summary>
        /// 性别
        /// </summary>
    public sex:string;
    
        /// <summary>
        /// 证件类型
        /// </summary>
    public certificate_type:string;
    
        /// <summary>
        /// 证件号码
        /// </summary>
    public certificate_code:string;
    
        /// <summary>
        /// 联系电话
        /// </summary>
    public contact_phone:string;
    
        /// <summary>
        /// 联系地址
        /// </summary>
    public contact_address:string;
    
        /// <summary>
        /// 邮箱
        /// </summary>
    public email:string;
    
        /// <summary>
        /// 籍贯
        /// </summary>
    public native_place:string;
    
        /// <summary>
        /// 民族
        /// </summary>
    public nationality:string;
    
        /// <summary>
        /// 出生日期
        /// </summary>
    public birthday:Date;
    
        /// <summary>
        /// 国籍
        /// </summary>
    public country:string;
    
        /// <summary>
        /// 省份
        /// </summary>
    public province:string;
    
        /// <summary>
        /// 城市
        /// </summary>
    public city:string;
    
        /// <summary>
        /// 区县
        /// </summary>
    public county:string;
    
        /// <summary>
        /// 组织机构名称
        /// </summary>
    public organ_name:string;
    
        /// <summary>
        /// 组织机构英文名称
        /// </summary>
    public organ_eng_name:string;
    
        /// <summary>
        /// 组织机构现状
        /// </summary>
    public organ_now_status:string;
    
        /// <summary>
        /// 组织机构代码
        /// </summary>
    public organ_code:string;
    
        /// <summary>
        /// 发证日期
        /// </summary>
    public certificate_time:Date;
    
        /// <summary>
        /// 有效期起
        /// </summary>
    public validity_start:Date;
    
        /// <summary>
        /// 有效期止
        /// </summary>
    public validity_end:Date;
    
        /// <summary>
        /// 机构类型
        /// </summary>
    public organ_kind:string;
    
        /// <summary>
        /// 企业类别名称
        /// </summary>
    public enterprise_name:string;
    
        /// <summary>
        /// 企业类别代码
        /// </summary>
    public enterprise_code:string;
    
        /// <summary>
        /// 法定代表人
        /// </summary>
    public legal_person:string;
    
        /// <summary>
        /// 法定代表人类型
        /// </summary>
    public legal_type:string;
    
        /// <summary>
        /// 法人证件名称
        /// </summary>
    public legal_name:string;
    
        /// <summary>
        /// 法人证件号码
        /// </summary>
    public legal_number:string;
    
        /// <summary>
        /// 登记注册日期
        /// </summary>
    public register_date:Date;
    
        /// <summary>
        /// 单位注册地址
        /// </summary>
    public register_address:string;
    
        /// <summary>
        /// 状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// 个人或企业
        /// </summary>
    public one_or_enterprises:string;
}

