//-----------------------------------------------------------------------
// <copyright file=" gk_dangerous_goodslist.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_dangerous_goodslist.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// gk_dangerous_goodslist Entity Model
    /// </summary>    
    [Table("gk_dangerous_goodslist")]
    public class gk_dangerous_goodslist
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 危险货物名称
        /// </summary>
        public string danger_name { get; set; }
    
        /// <summary>
        /// 危险货物编号
        /// </summary>
        public string danger_number { get; set; }
    
        /// <summary>
        /// 别名
        /// </summary>
        public string danger_alias { get; set; }
    
        /// <summary>
        /// 英文名称
        /// </summary>
        public string english_name { get; set; }
    
        /// <summary>
        /// 联合国编号
        /// </summary>
        public string union_number { get; set; }
    
        /// <summary>
        /// 主要理化性质
        /// </summary>
        public string primary_prop { get; set; }
    
        /// <summary>
        /// 应急措施
        /// </summary>
        public string emergency_step { get; set; }
    
        /// <summary>
        /// CAS号
        /// </summary>
        public string cas_number { get; set; }
    
        /// <summary>
        /// 危险货物类别
        /// </summary>
        public string goods_category { get; set; }
    }
}
