//-----------------------------------------------------------------------
// <copyright file=" gk_dangerous_goodslist.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_dangerous_goodslist.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_dangerous_goodslist Entity Model
    /// </summary>    
export class gk_dangerous_goodslist
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 危险货物名称
        /// </summary>
    public danger_name:string;
    
        /// <summary>
        /// 危险货物编号
        /// </summary>
    public danger_number:string;
    
        /// <summary>
        /// 别名
        /// </summary>
    public danger_alias:string;
    
        /// <summary>
        /// 英文名称
        /// </summary>
    public english_name:string;
    
        /// <summary>
        /// 联合国编号
        /// </summary>
    public union_number:string;
    
        /// <summary>
        /// 主要理化性质
        /// </summary>
    public primary_prop:string;
    
        /// <summary>
        /// 应急措施
        /// </summary>
    public emergency_step:string;
    
        /// <summary>
        /// CAS号
        /// </summary>
    public cas_number:string;
    
        /// <summary>
        /// 危险货物类别
        /// </summary>
    public goods_category:string;
}

