//-----------------------------------------------------------------------
// <copyright file=" gk_fire_check.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_fire_check.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// gk_fire_check Entity Model
    /// </summary>    
    [Serializable]
    public class gk_fire_check
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 申请人类别
        /// </summary>
        public string one_or_enterprises { get; set; }
    
        /// <summary>
        /// 申请人名称
        /// </summary>
        public string name { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        public string sex { get; set; }
    
        /// <summary>
        /// 证件类型
        /// </summary>
        public string certificate_type { get; set; }
    
        /// <summary>
        /// 证件号码
        /// </summary>
        public string certificate_code { get; set; }
    
        /// <summary>
        /// 联系电话
        /// </summary>
        public string contact_phone { get; set; }
    
        /// <summary>
        /// 联系地址
        /// </summary>
        public string contact_address { get; set; }
    
        /// <summary>
        /// 邮箱
        /// </summary>
        public string email { get; set; }
    
        /// <summary>
        /// 籍贯
        /// </summary>
        public string native_place { get; set; }
    
        /// <summary>
        /// 民族
        /// </summary>
        public string nationality { get; set; }
    
        /// <summary>
        /// 出生日期
        /// </summary>
        public DateTime birthday { get; set; }
    
        /// <summary>
        /// 国籍
        /// </summary>
        public string country { get; set; }
    
        /// <summary>
        /// 省份
        /// </summary>
        public string province { get; set; }
    
        /// <summary>
        /// 城市
        /// </summary>
        public string city { get; set; }
    
        /// <summary>
        /// 区县
        /// </summary>
        public string county { get; set; }
    
        /// <summary>
        /// 组织机构名称
        /// </summary>
        public string organ_name { get; set; }
    
        /// <summary>
        /// 组织机构英文名称
        /// </summary>
        public string organ_eng_name { get; set; }
    
        /// <summary>
        /// 组织机构现状
        /// </summary>
        public string organ_now_status { get; set; }
    
        /// <summary>
        /// 组织机构代码
        /// </summary>
        public string organ_code { get; set; }
    
        /// <summary>
        /// 发证日期
        /// </summary>
        public DateTime certificate_time { get; set; }
    
        /// <summary>
        /// 有效期起
        /// </summary>
        public DateTime validity_start { get; set; }
    
        /// <summary>
        /// 有效期止
        /// </summary>
        public DateTime validity_end { get; set; }
    
        /// <summary>
        /// 企业类型
        /// </summary>
        public string enterprise_name { get; set; }
    
        /// <summary>
        /// 法定代表人
        /// </summary>
        public string legal_person { get; set; }
    
        /// <summary>
        /// 法定代表人类型
        /// </summary>
        public string legal_person_ty { get; set; }
    
        /// <summary>
        /// 法人联系方式
        /// </summary>
        public string legal_phone { get; set; }
    
        /// <summary>
        /// 法人证件名称
        /// </summary>
        public string legal_name { get; set; }
    
        /// <summary>
        /// 法人证件号码
        /// </summary>
        public string legal_number { get; set; }
    
        /// <summary>
        /// 登记注册日期
        /// </summary>
        public DateTime register_date { get; set; }
    
        /// <summary>
        /// 单位注册地址
        /// </summary>
        public string register_address { get; set; }
    
        /// <summary>
        /// 行政部门同意文书或复印件
        /// </summary>
        public string is_agree { get; set; }
    
        /// <summary>
        /// 安全及防污染措施及证明材料
        /// </summary>
        public string is_materials { get; set; }
    
        /// <summary>
        /// 与采掘爆破有关的合同或协议书
        /// </summary>
        public string is_protocol { get; set; }
    
        /// <summary>
        /// 作业单位资质认证文书
        /// </summary>
        public string is_approve { get; set; }
    
        /// <summary>
        /// 施工作业船舶证书和船员证书
        /// </summary>
        public string is_ship_cert { get; set; }
    
        /// <summary>
        /// 专项维护申请
        /// </summary>
        public string is_maintain_apply { get; set; }
    
        /// <summary>
        /// 已通过评审的通航安全报告
        /// </summary>
        public string is_safety { get; set; }
    
        /// <summary>
        /// 航行通告发布申请
        /// </summary>
        public string is_ship_apply { get; set; }
    
        /// <summary>
        /// 委托证明及委托双方的身份证明
        /// </summary>
        public string is_idcard { get; set; }
    
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime work_apply_date { get; set; }
    
        /// <summary>
        /// 施工作业或活动程序
        /// </summary>
        public string work_photo { get; set; }
    
        /// <summary>
        /// 状态
        /// </summary>
        public string status { get; set; }
    }
}
