//-----------------------------------------------------------------------
// <copyright file=" gk_operator_baseinfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_baseinfo.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// gk_operator_baseinfo Entity Model
    /// </summary>    
    [Table("gk_operator_baseinfo")]
    public class gk_operator_baseinfo : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _port_name;
        /// <summary>
        /// 港口名称
        /// </summary>
        public string port_name
        {
            get { return _port_name; }
            set { updateProper(ref _port_name, value);}
        }
    
        private string _river_name;
        /// <summary>
        /// 河流名称
        /// </summary>
        public string river_name
        {
            get { return _river_name; }
            set { updateProper(ref _river_name, value);}
        }
    
        private string _belong_water;
        /// <summary>
        /// 港口所在地海区
        /// </summary>
        public string belong_water
        {
            get { return _belong_water; }
            set { updateProper(ref _belong_water, value);}
        }
    
        private string _belong_harbour;
        /// <summary>
        /// 港口所在港湾
        /// </summary>
        public string belong_harbour
        {
            get { return _belong_harbour; }
            set { updateProper(ref _belong_harbour, value);}
        }
    
        private string _customs_name;
        /// <summary>
        /// 海关名称
        /// </summary>
        public string customs_name
        {
            get { return _customs_name; }
            set { updateProper(ref _customs_name, value);}
        }
    
        private string _web_portal;
        /// <summary>
        /// 港口门户网站
        /// </summary>
        public string web_portal
        {
            get { return _web_portal; }
            set { updateProper(ref _web_portal, value);}
        }
    
        private string _has_merger;
        /// <summary>
        /// 是否经过合并
        /// </summary>
        public string has_merger
        {
            get { return _has_merger; }
            set { updateProper(ref _has_merger, value);}
        }
    
        private string _old_name;
        /// <summary>
        /// 被合并港口原名称
        /// </summary>
        public string old_name
        {
            get { return _old_name; }
            set { updateProper(ref _old_name, value);}
        }
    
        private string _has_reply;
        /// <summary>
        /// 总体规划是否批复
        /// </summary>
        public string has_reply
        {
            get { return _has_reply; }
            set { updateProper(ref _has_reply, value);}
        }
    
        private string _reply_no;
        /// <summary>
        /// 总体规划批复文号
        /// </summary>
        public string reply_no
        {
            get { return _reply_no; }
            set { updateProper(ref _reply_no, value);}
        }
    
        private string _remark;
        /// <summary>
        /// 备注
        /// </summary>
        public string remark
        {
            get { return _remark; }
            set { updateProper(ref _remark, value);}
        }
    }
}
