//-----------------------------------------------------------------------
// <copyright file=" gk_operator_personnel.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_personnel.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// gk_operator_personnel Entity Model
    /// </summary>    
    [Table("gk_operator_personnel")]
    public class gk_operator_personnel : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _official_manager_num;
        /// <summary>
        /// 正式合同管理人员数量
        /// </summary>
        public string official_manager_num
        {
            get { return _official_manager_num; }
            set { updateProper(ref _official_manager_num, value);}
        }
    
        private string _official_staff_num;
        /// <summary>
        /// 正式合同作业人员数量
        /// </summary>
        public string official_staff_num
        {
            get { return _official_staff_num; }
            set { updateProper(ref _official_staff_num, value);}
        }
    
        private string _peripheral_manager_num;
        /// <summary>
        /// 外围人员管理人员数量
        /// </summary>
        public string peripheral_manager_num
        {
            get { return _peripheral_manager_num; }
            set { updateProper(ref _peripheral_manager_num, value);}
        }
    
        private string _peripheral_staff_num;
        /// <summary>
        /// 外围人员作业人员数量
        /// </summary>
        public string peripheral_staff_num
        {
            get { return _peripheral_staff_num; }
            set { updateProper(ref _peripheral_staff_num, value);}
        }
    
        private string _outsource_staff_num;
        /// <summary>
        /// 外围人员劳务外包人员数量
        /// </summary>
        public string outsource_staff_num
        {
            get { return _outsource_staff_num; }
            set { updateProper(ref _outsource_staff_num, value);}
        }
    
        private string _operator_id;
        /// <summary>
        /// 关联
        /// </summary>
        public string operator_id
        {
            get { return _operator_id; }
            set { updateProper(ref _operator_id, value);}
        }
    }
}
