//-----------------------------------------------------------------------
// <copyright file=" gk_operator_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_info.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_operator_info Entity Model
    /// </summary>    
export class gk_operator_info
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 所在地市港口管理部门
        /// </summary>
    public port_manager_dept:string;
    
        /// <summary>
        /// 港口经营人名称
        /// </summary>
    public port_operator_name:string;
    
        /// <summary>
        /// 法定代表人
        /// </summary>
    public legal_person:string;
    
        /// <summary>
        /// 港口经营单位办公地址
        /// </summary>
    public port_operator_address:string;
    
        /// <summary>
        /// 经营类型
        /// </summary>
    public operator_type:string;
    
        /// <summary>
        /// 联系人
        /// </summary>
    public contact_name:string;
    
        /// <summary>
        /// 联系电话
        /// </summary>
    public contact_tel:string;
    
        /// <summary>
        /// 传真
        /// </summary>
    public fax:string;
    
        /// <summary>
        /// 电子邮箱
        /// </summary>
    public email:string;
    
        /// <summary>
        /// 邮编
        /// </summary>
    public postcode:string;
    
        /// <summary>
        /// 是否为主城区
        /// </summary>
    public has_main_city:string;
    
        /// <summary>
        /// 港口类型
        /// </summary>
    public port_type:string;
    
        /// <summary>
        /// 附件
        /// </summary>
    public enclosure_path:string;
    
        /// <summary>
        /// 岸线批复文件
        /// </summary>
    public approval_document:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public remark:string;
}

