//-----------------------------------------------------------------------
// <copyright file=" gk_operator_region.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_region.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// gk_operator_region Entity Model
    /// </summary>    
    [Table("gk_operator_region")]
    public class gk_operator_region : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _land_area;
        /// <summary>
        /// 使用陆域土地面积
        /// </summary>
        public string land_area
        {
            get { return _land_area; }
            set { updateProper(ref _land_area, value);}
        }
    
        private string _land_approval_no;
        /// <summary>
        /// 使用陆域土地相关批文及文号
        /// </summary>
        public string land_approval_no
        {
            get { return _land_approval_no; }
            set { updateProper(ref _land_approval_no, value);}
        }
    
        private string _water_area;
        /// <summary>
        /// 使用水域面积
        /// </summary>
        public string water_area
        {
            get { return _water_area; }
            set { updateProper(ref _water_area, value);}
        }
    
        private string _water_approval_no;
        /// <summary>
        /// 使用水域相关批文及文号
        /// </summary>
        public string water_approval_no
        {
            get { return _water_approval_no; }
            set { updateProper(ref _water_approval_no, value);}
        }
    
        private string _nature_shoreline_length;
        /// <summary>
        /// 使用自然岸线长度
        /// </summary>
        public string nature_shoreline_length
        {
            get { return _nature_shoreline_length; }
            set { updateProper(ref _nature_shoreline_length, value);}
        }
    
        private string _shoreline_approval_no;
        /// <summary>
        /// 使用自然岸线相关批文及文号
        /// </summary>
        public string shoreline_approval_no
        {
            get { return _shoreline_approval_no; }
            set { updateProper(ref _shoreline_approval_no, value);}
        }
    
        private string _operator_id;
        /// <summary>
        /// 关联港口经营人ID
        /// </summary>
        public string operator_id
        {
            get { return _operator_id; }
            set { updateProper(ref _operator_id, value);}
        }
    
        private string _scan_img;
        /// <summary>
        /// 涉及批文或证书扫描件
        /// </summary>
        public string scan_img
        {
            get { return _scan_img; }
            set { updateProper(ref _scan_img, value);}
        }
    }
}
