//-----------------------------------------------------------------------
// <copyright file=" gk_operator_baseinfo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_baseinfo.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_operator_baseinfo Entity Model
    /// </summary>    
export class gk_operator_baseinfo
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 港口名称
        /// </summary>
    public port_name:string;
    
        /// <summary>
        /// 河流名称
        /// </summary>
    public river_name:string;
    
        /// <summary>
        /// 港口所在地海区
        /// </summary>
    public belong_water:string;
    
        /// <summary>
        /// 港口所在港湾
        /// </summary>
    public belong_harbour:string;
    
        /// <summary>
        /// 海关名称
        /// </summary>
    public customs_name:string;
    
        /// <summary>
        /// 港口门户网站
        /// </summary>
    public web_portal:string;
    
        /// <summary>
        /// 是否经过合并
        /// </summary>
    public has_merger:string;
    
        /// <summary>
        /// 被合并港口原名称
        /// </summary>
    public old_name:string;
    
        /// <summary>
        /// 总体规划是否批复
        /// </summary>
    public has_reply:string;
    
        /// <summary>
        /// 总体规划批复文号
        /// </summary>
    public reply_no:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public remark:string;
}

