//-----------------------------------------------------------------------
// <copyright file=" gk_operator_invest.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_invest.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_operator_invest Entity Model
    /// </summary>    
export class gk_operator_invest
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 投资人名称
        /// </summary>
    public invest_name:string;
    
        /// <summary>
        /// 是否外商投资
        /// </summary>
    public has_foreign_businessman:string;
    
        /// <summary>
        /// 投资金额
        /// </summary>
    public invest_num:string;
    
        /// <summary>
        /// 金额单位
        /// </summary>
    public invest_unit:string;
    
        /// <summary>
        /// 所占份额
        /// </summary>
    public invest_portion:string;
    
        /// <summary>
        /// 注册地址
        /// </summary>
    public register_address:string;
    
        /// <summary>
        /// 关联ID
        /// </summary>
    public operator_id:string;
}

