//-----------------------------------------------------------------------
// <copyright file=" gk_operator_berth.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_berth.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// gk_operator_berth Entity Model
    /// </summary>    
export class gk_operator_berth
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 泊位名称
        /// </summary>
    public berth_name:string;
    
        /// <summary>
        /// 所在港区名称
        /// </summary>
    public harbour_name:string;
    
        /// <summary>
        /// 所在码头名称
        /// </summary>
    public wharf_name:string;
    
        /// <summary>
        /// 泊位属性
        /// </summary>
    public berth_prop:string;
    
        /// <summary>
        /// 泊位型式
        /// </summary>
    public berth_type:string;
    
        /// <summary>
        /// 泊位主要用途
        /// </summary>
    public berth_use:string;
    
        /// <summary>
        /// 专业化泊位分类
        /// </summary>
    public berth_kind:string;
    
        /// <summary>
        /// 码头前沿设计水深
        /// </summary>
    public design_deep:string;
    
        /// <summary>
        /// 码头前沿维护水深
        /// </summary>
    public maintain_deep:string;
    
        /// <summary>
        /// 设计靠泊能力
        /// </summary>
    public design_berth:string;
    
        /// <summary>
        /// 结构靠泊能力
        /// </summary>
    public structure_berth:string;
    
        /// <summary>
        /// 核查靠泊能力
        /// </summary>
    public check_berth:string;
    
        /// <summary>
        /// 核查能力限制条件
        /// </summary>
    public check_limit:string;
    
        /// <summary>
        /// 泊位利用率
        /// </summary>
    public berth_ratio:string;
    
        /// <summary>
        /// 设计年散装或件杂通过能力
        /// </summary>
    public design_bulk_pass:string;
    
        /// <summary>
        /// 设计年集装箱通过能力TEU
        /// </summary>
    public design_container_pass:string;
    
        /// <summary>
        /// 设计年滚装通过能力万标量
        /// </summary>
    public design_roll_pass:string;
    
        /// <summary>
        /// 设计年旅客通过能力
        /// </summary>
    public design_passenger_pass:string;
    
        /// <summary>
        /// 核查年散装或件杂通过能力
        /// </summary>
    public check_bulk_pass:string;
    
        /// <summary>
        /// 核查年集装箱通过能力TEU
        /// </summary>
    public check_container_pass:string;
    
        /// <summary>
        /// 核查年滚装通过能力万标量
        /// </summary>
    public check_roll_pass:string;
    
        /// <summary>
        /// 核查年旅客通过能力
        /// </summary>
    public check_passenger_pass:string;
    
        /// <summary>
        /// 估算年散装或件杂通过能力
        /// </summary>
    public estimate_bulk_pass:string;
    
        /// <summary>
        /// 估算年集装箱通过能力
        /// </summary>
    public estimate_container_pass:string;
    
        /// <summary>
        /// 估算年滚装通过能力万标量
        /// </summary>
    public estimate_roll_pass:string;
    
        /// <summary>
        /// 估算年旅客通过能力
        /// </summary>
    public estimate_passenger_pass:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public remark:string;
    
        /// <summary>
        /// 关联id
        /// </summary>
    public operator_id:string;
    
        /// <summary>
        /// 设计年集装箱通过能力
        /// </summary>
    public design_container_pass_dun:string;
    
        /// <summary>
        /// 设计年滚装通过能力
        /// </summary>
    public design_roll_pass_jie:string;
    
        /// <summary>
        /// 核查年集装箱通过能力
        /// </summary>
    public check_container_dun:string;
    
        /// <summary>
        /// 估算年滚装通过能力
        /// </summary>
    public estimate_roll_pass_jie:string;
    
        /// <summary>
        /// 估算年集装箱通过能力
        /// </summary>
    public estimate_container_pass_dun:string;
    
        /// <summary>
        /// 核查年滚装通过能力
        /// </summary>
    public check_roll_pass_jie:string;
    
        /// <summary>
        /// 泊位长度
        /// </summary>
    public berth_length:string;
}

