//-----------------------------------------------------------------------
// <copyright file=" gk_operator_yard.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_operator_yard.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// gk_operator_yard Entity Model
    /// </summary>    
    [Table("gk_operator_yard")]
    public class gk_operator_yard : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _harbour_name;
        /// <summary>
        /// 所在港区名称
        /// </summary>
        public string harbour_name
        {
            get { return _harbour_name; }
            set { updateProper(ref _harbour_name, value);}
        }
    
        private string _yard_name;
        /// <summary>
        /// 堆场名称
        /// </summary>
        public string yard_name
        {
            get { return _yard_name; }
            set { updateProper(ref _yard_name, value);}
        }
    
        private string _production_type;
        /// <summary>
        /// 生产类型
        /// </summary>
        public string production_type
        {
            get { return _production_type; }
            set { updateProper(ref _production_type, value);}
        }
    
        private string _main_use;
        /// <summary>
        /// 主要用途
        /// </summary>
        public string main_use
        {
            get { return _main_use; }
            set { updateProper(ref _main_use, value);}
        }
    
        private string _yard_area;
        /// <summary>
        /// 堆场总面积
        /// </summary>
        public string yard_area
        {
            get { return _yard_area; }
            set { updateProper(ref _yard_area, value);}
        }
    
        private string _yard_volume;
        /// <summary>
        /// 堆场总容量
        /// </summary>
        public string yard_volume
        {
            get { return _yard_volume; }
            set { updateProper(ref _yard_volume, value);}
        }
    
        private string _yard_store_prop;
        /// <summary>
        /// 堆场总堆存能力
        /// </summary>
        public string yard_store_prop
        {
            get { return _yard_store_prop; }
            set { updateProper(ref _yard_store_prop, value);}
        }
    
        private string _coal_area;
        /// <summary>
        /// 煤炭堆场面积
        /// </summary>
        public string coal_area
        {
            get { return _coal_area; }
            set { updateProper(ref _coal_area, value);}
        }
    
        private string _coal_volume;
        /// <summary>
        /// 煤炭堆场容量
        /// </summary>
        public string coal_volume
        {
            get { return _coal_volume; }
            set { updateProper(ref _coal_volume, value);}
        }
    
        private string _kuang_area;
        /// <summary>
        /// 矿石面积
        /// </summary>
        public string kuang_area
        {
            get { return _kuang_area; }
            set { updateProper(ref _kuang_area, value);}
        }
    
        private string _container_area;
        /// <summary>
        /// 集装箱堆场面积
        /// </summary>
        public string container_area
        {
            get { return _container_area; }
            set { updateProper(ref _container_area, value);}
        }
    
        private string _container_prop;
        /// <summary>
        /// 集装箱堆场堆存能力
        /// </summary>
        public string container_prop
        {
            get { return _container_prop; }
            set { updateProper(ref _container_prop, value);}
        }
    
        private string _kuang_volume;
        /// <summary>
        /// 矿石容量
        /// </summary>
        public string kuang_volume
        {
            get { return _kuang_volume; }
            set { updateProper(ref _kuang_volume, value);}
        }
    
        private string _cold_store_area;
        /// <summary>
        /// 冷藏箱堆场面积
        /// </summary>
        public string cold_store_area
        {
            get { return _cold_store_area; }
            set { updateProper(ref _cold_store_area, value);}
        }
    
        private string _cold_store_prop;
        /// <summary>
        /// 冷藏箱堆场堆存能力
        /// </summary>
        public string cold_store_prop
        {
            get { return _cold_store_prop; }
            set { updateProper(ref _cold_store_prop, value);}
        }
    
        private string _danger_area;
        /// <summary>
        /// 危险品箱堆场面积
        /// </summary>
        public string danger_area
        {
            get { return _danger_area; }
            set { updateProper(ref _danger_area, value);}
        }
    
        private string _danger_store_prop;
        /// <summary>
        /// 危险品箱堆场堆存能力
        /// </summary>
        public string danger_store_prop
        {
            get { return _danger_store_prop; }
            set { updateProper(ref _danger_store_prop, value);}
        }
    
        private string _dismounting_area;
        /// <summary>
        /// 拆装箱场面积
        /// </summary>
        public string dismounting_area
        {
            get { return _dismounting_area; }
            set { updateProper(ref _dismounting_area, value);}
        }
    
        private string _dismounting_store_prop;
        /// <summary>
        /// 拆装箱场堆存能力
        /// </summary>
        public string dismounting_store_prop
        {
            get { return _dismounting_store_prop; }
            set { updateProper(ref _dismounting_store_prop, value);}
        }
    
        private string _wash_area;
        /// <summary>
        /// 洗箱场面积
        /// </summary>
        public string wash_area
        {
            get { return _wash_area; }
            set { updateProper(ref _wash_area, value);}
        }
    
        private string _wash_store_prop;
        /// <summary>
        /// 洗箱场堆存能力
        /// </summary>
        public string wash_store_prop
        {
            get { return _wash_store_prop; }
            set { updateProper(ref _wash_store_prop, value);}
        }
    
        private string _other_area;
        /// <summary>
        /// 其他堆场面积
        /// </summary>
        public string other_area
        {
            get { return _other_area; }
            set { updateProper(ref _other_area, value);}
        }
    
        private string _other_volume;
        /// <summary>
        /// 其他堆场容量
        /// </summary>
        public string other_volume
        {
            get { return _other_volume; }
            set { updateProper(ref _other_volume, value);}
        }
    
        private string _other_store_prop;
        /// <summary>
        /// 其他堆场面积堆存能力
        /// </summary>
        public string other_store_prop
        {
            get { return _other_store_prop; }
            set { updateProper(ref _other_store_prop, value);}
        }
    
        private string _operator_id;
        /// <summary>
        /// 关联id
        /// </summary>
        public string operator_id
        {
            get { return _operator_id; }
            set { updateProper(ref _operator_id, value);}
        }
    }
}
