//-----------------------------------------------------------------------
// <copyright file=" gk_safe_check.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: gk_safe_check.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// gk_safe_check Entity Model
    /// </summary>    
    [Table("gk_safe_check")]
    public class gk_safe_check
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 项目名称
        /// </summary>
        public string project_name { get; set; }
    
        /// <summary>
        /// 负责人
        /// </summary>
        public string duty_man { get; set; }
    
        /// <summary>
        /// 项目类别
        /// </summary>
        public string project_sort { get; set; }
    
        /// <summary>
        /// 联系人
        /// </summary>
        public string contact_person { get; set; }
    
        /// <summary>
        /// 申请单位
        /// </summary>
        public string apply_unit { get; set; }
    
        /// <summary>
        /// 联系电话
        /// </summary>
        public string phone { get; set; }
    
        /// <summary>
        /// 传真
        /// </summary>
        public string fax { get; set; }
    
        /// <summary>
        /// 申请事项
        /// </summary>
        public string apply_thing { get; set; }
    
        /// <summary>
        /// 单位地址
        /// </summary>
        public string unit_address { get; set; }
    
        /// <summary>
        /// 工程地址
        /// </summary>
        public string project_address { get; set; }
    
        /// <summary>
        /// 工程开始时间
        /// </summary>
        public DateTime? project_begin_time { get; set; }
    
        /// <summary>
        /// 工程结束时间
        /// </summary>
        public DateTime? project_end_time { get; set; }
    
        /// <summary>
        /// 港口建设项目概况
        /// </summary>
        public string general_situation { get; set; }
    
        /// <summary>
        /// 装卸储存主要危险货物品名
        /// </summary>
        public string danger_goods { get; set; }
    
        /// <summary>
        /// 状态
        /// </summary>
        public string status { get; set; }
    
        /// <summary>
        /// 规划选址文件名称
        /// </summary>
        public string paper_name { get; set; }
    
        /// <summary>
        /// 岸线批复文件名称
        /// </summary>
        public string reply_name { get; set; }
    
        /// <summary>
        /// 选址条件是否合法
        /// </summary>
        public string is_address_legal { get; set; }
    
        /// <summary>
        /// 规划选址文件发文机构
        /// </summary>
        public string paper_organ { get; set; }
    
        /// <summary>
        /// 安全预评价报告是否存在缺漏
        /// </summary>
        public string is_gaps { get; set; }
    
        /// <summary>
        /// 建设规模
        /// </summary>
        public string build_scale { get; set; }
    
        /// <summary>
        /// 是否有隐瞒或提供虚假文件
        /// </summary>
        public string is_hidden { get; set; }
    
        /// <summary>
        /// 主要技术工艺是否合法
        /// </summary>
        public string is_main_legal { get; set; }
    
        /// <summary>
        /// 储罐用量
        /// </summary>
        public string storage_tank { get; set; }
    
        /// <summary>
        /// 岸线批复文件文号
        /// </summary>
        public string reply_no { get; set; }
    
        /// <summary>
        /// 资质等级
        /// </summary>
        public string aptitude_level { get; set; }
    
        /// <summary>
        /// 是否依法进行安全论证与评估
        /// </summary>
        public string is_argument { get; set; }
    
        /// <summary>
        /// 安全预评价报告对策是否合法
        /// </summary>
        public string is_legal { get; set; }
    
        /// <summary>
        /// 所在水域
        /// </summary>
        public string place_river { get; set; }
    
        /// <summary>
        /// 评价机构名称
        /// </summary>
        public string organization_name { get; set; }
    
        /// <summary>
        /// 资质证书号
        /// </summary>
        public string aptitude_no { get; set; }
    
        /// <summary>
        /// 规划选址文件文号
        /// </summary>
        public string paper_no { get; set; }
    
        /// <summary>
        /// 安全预评价报告名称
        /// </summary>
        public string report_name { get; set; }
    
        /// <summary>
        /// 岸线批复文件发文机构
        /// </summary>
        public string reply_organ { get; set; }
    }
}
