//-----------------------------------------------------------------------
// <copyright file=" item.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: item.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// item Entity Model
    /// </summary>    
    [Table("item")]
    public class item
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 事项名称
        /// </summary>
        public string item_name { get; set; }
    
        /// <summary>
        /// 事项编码
        /// </summary>
        public string item_code { get; set; }
    }
}
