//-----------------------------------------------------------------------
// <copyright file=" jeecg_order_custom.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_order_custom.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// jeecg_order_custom Entity Model
    /// </summary>    
    [Table("jeecg_order_custom")]
    public class jeecg_order_custom
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CREATE_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? DEL_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int? DELFLAG { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GO_ORDER_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_BUSS_CONTENT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_CONTENT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_CUS_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_IDCARD { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_PASSPORT_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GOC_SEX { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? MODIFY_DT { get; set; }
    }
}
