//-----------------------------------------------------------------------
// <copyright file=" jeecg_custom_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_custom_info.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jeecg_custom_info Entity Model
    /// </summary>    
    [Table("jeecg_custom_info")]
    public class jeecg_custom_info : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _cust_name;
        /// <summary>
        /// 客户名称
        /// </summary>
        public string cust_name
        {
            get { return _cust_name; }
            set { updateProper(ref _cust_name, value);}
        }
    
        private string _cust_addr;
        /// <summary>
        /// 地址
        /// </summary>
        public string cust_addr
        {
            get { return _cust_addr; }
            set { updateProper(ref _cust_addr, value);}
        }
    
        private string _cust_code;
        /// <summary>
        /// 客户编号
        /// </summary>
        public string cust_code
        {
            get { return _cust_code; }
            set { updateProper(ref _cust_code, value);}
        }
    
        private string _email;
        /// <summary>
        /// email
        /// </summary>
        public string email
        {
            get { return _email; }
            set { updateProper(ref _email, value);}
        }
    
        private string _cust_charge;
        /// <summary>
        /// 负责人
        /// </summary>
        public string cust_charge
        {
            get { return _cust_charge; }
            set { updateProper(ref _cust_charge, value);}
        }
    
        private string _sex;
        /// <summary>
        /// 性别
        /// </summary>
        public string sex
        {
            get { return _sex; }
            set { updateProper(ref _sex, value);}
        }
    
        private string _age;
        /// <summary>
        /// 年龄
        /// </summary>
        public string age
        {
            get { return _age; }
            set { updateProper(ref _age, value);}
        }
    
        private string _position;
        /// <summary>
        /// 职务
        /// </summary>
        public string position
        {
            get { return _position; }
            set { updateProper(ref _position, value);}
        }
    
        private string _phone;
        /// <summary>
        /// 电话
        /// </summary>
        public string phone
        {
            get { return _phone; }
            set { updateProper(ref _phone, value);}
        }
    
        private string _bank;
        /// <summary>
        /// 往来银行
        /// </summary>
        public string bank
        {
            get { return _bank; }
            set { updateProper(ref _bank, value);}
        }
    
        private string _money;
        /// <summary>
        /// 现金情况
        /// </summary>
        public string money
        {
            get { return _money; }
            set { updateProper(ref _money, value);}
        }
    
        private string _promoter;
        /// <summary>
        /// 承办人
        /// </summary>
        public string promoter
        {
            get { return _promoter; }
            set { updateProper(ref _promoter, value);}
        }
    
        private string _account;
        /// <summary>
        /// 账号
        /// </summary>
        public string account
        {
            get { return _account; }
            set { updateProper(ref _account, value);}
        }
    
        private string _turnover;
        /// <summary>
        /// 资金周转
        /// </summary>
        public string turnover
        {
            get { return _turnover; }
            set { updateProper(ref _turnover, value);}
        }
    
        private string _payment_attr;
        /// <summary>
        /// 付款态度
        /// </summary>
        public string payment_attr
        {
            get { return _payment_attr; }
            set { updateProper(ref _payment_attr, value);}
        }
    
        private string _sax_num;
        /// <summary>
        /// 税号
        /// </summary>
        public string sax_num
        {
            get { return _sax_num; }
            set { updateProper(ref _sax_num, value);}
        }
    
        private string _pay_date;
        /// <summary>
        /// 付款日期
        /// </summary>
        public string pay_date
        {
            get { return _pay_date; }
            set { updateProper(ref _pay_date, value);}
        }
    
        private string _begin_pay_date;
        /// <summary>
        /// 开始交易日期
        /// </summary>
        public string begin_pay_date
        {
            get { return _begin_pay_date; }
            set { updateProper(ref _begin_pay_date, value);}
        }
    
        private string _main_bus;
        /// <summary>
        /// 主营产品
        /// </summary>
        public string main_bus
        {
            get { return _main_bus; }
            set { updateProper(ref _main_bus, value);}
        }
    
        private string _bus_pro;
        /// <summary>
        /// 营业项目
        /// </summary>
        public string bus_pro
        {
            get { return _bus_pro; }
            set { updateProper(ref _bus_pro, value);}
        }
    
        private string _warehouse;
        /// <summary>
        /// 仓库情况
        /// </summary>
        public string warehouse
        {
            get { return _warehouse; }
            set { updateProper(ref _warehouse, value);}
        }
    
        private string _people;
        /// <summary>
        /// 员工人数及素质
        /// </summary>
        public string people
        {
            get { return _people; }
            set { updateProper(ref _people, value);}
        }
    
        private string _transportation;
        /// <summary>
        /// 运输方式
        /// </summary>
        public string transportation
        {
            get { return _transportation; }
            set { updateProper(ref _transportation, value);}
        }
    
        private string _operation;
        /// <summary>
        /// 经营体制
        /// </summary>
        public string operation
        {
            get { return _operation; }
            set { updateProper(ref _operation, value);}
        }
    
        private string _car;
        /// <summary>
        /// 服务车数目
        /// </summary>
        public string car
        {
            get { return _car; }
            set { updateProper(ref _car, value);}
        }
    
        private string _shopkeeper;
        /// <summary>
        /// 零售商数及覆盖情况
        /// </summary>
        public string shopkeeper
        {
            get { return _shopkeeper; }
            set { updateProper(ref _shopkeeper, value);}
        }
    
        private string _wholesale;
        /// <summary>
        /// 批发商数
        /// </summary>
        public string wholesale
        {
            get { return _wholesale; }
            set { updateProper(ref _wholesale, value);}
        }
    
        private string _bus_scope;
        /// <summary>
        /// 营业范围
        /// </summary>
        public string bus_scope
        {
            get { return _bus_scope; }
            set { updateProper(ref _bus_scope, value);}
        }
    
        private string _area;
        /// <summary>
        /// 门市面积
        /// </summary>
        public string area
        {
            get { return _area; }
            set { updateProper(ref _area, value);}
        }
    
        private string _management;
        /// <summary>
        /// 经营方针
        /// </summary>
        public string management
        {
            get { return _management; }
            set { updateProper(ref _management, value);}
        }
    
        private string _stock1;
        /// <summary>
        /// 进货
        /// </summary>
        public string stock1
        {
            get { return _stock1; }
            set { updateProper(ref _stock1, value);}
        }
    
        private string _stock2;
        /// <summary>
        /// 进货
        /// </summary>
        public string stock2
        {
            get { return _stock2; }
            set { updateProper(ref _stock2, value);}
        }
    
        private string _sale1;
        /// <summary>
        /// 销售
        /// </summary>
        public string sale1
        {
            get { return _sale1; }
            set { updateProper(ref _sale1, value);}
        }
    
        private string _sale2;
        /// <summary>
        /// 销售
        /// </summary>
        public string sale2
        {
            get { return _sale2; }
            set { updateProper(ref _sale2, value);}
        }
    
        private string _inventory1;
        /// <summary>
        /// 存货
        /// </summary>
        public string inventory1
        {
            get { return _inventory1; }
            set { updateProper(ref _inventory1, value);}
        }
    
        private string _inventory2;
        /// <summary>
        /// 存货
        /// </summary>
        public string inventory2
        {
            get { return _inventory2; }
            set { updateProper(ref _inventory2, value);}
        }
    
        private string _max_money;
        /// <summary>
        /// 最高信用额度
        /// </summary>
        public string max_money
        {
            get { return _max_money; }
            set { updateProper(ref _max_money, value);}
        }
    
        private string _cust_level;
        /// <summary>
        /// 客户等级
        /// </summary>
        public string cust_level
        {
            get { return _cust_level; }
            set { updateProper(ref _cust_level, value);}
        }
    
        private string _all_avg_inventory;
        /// <summary>
        /// 总体月均库存数
        /// </summary>
        public string all_avg_inventory
        {
            get { return _all_avg_inventory; }
            set { updateProper(ref _all_avg_inventory, value);}
        }
    
        private string _avg_inventory;
        /// <summary>
        /// 月均库存数
        /// </summary>
        public string avg_inventory
        {
            get { return _avg_inventory; }
            set { updateProper(ref _avg_inventory, value);}
        }
    
        private string _price;
        /// <summary>
        /// 价格折扣
        /// </summary>
        public string price
        {
            get { return _price; }
            set { updateProper(ref _price, value);}
        }
    
        private string _promise;
        /// <summary>
        /// 支持和服务的承诺
        /// </summary>
        public string promise
        {
            get { return _promise; }
            set { updateProper(ref _promise, value);}
        }
    
        private string _competing_goods;
        /// <summary>
        /// 竞品经营情况
        /// </summary>
        public string competing_goods
        {
            get { return _competing_goods; }
            set { updateProper(ref _competing_goods, value);}
        }
    }
}
