//-----------------------------------------------------------------------
// <copyright file=" jeecg_demo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_demo.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jeecg_demo Entity Model
    /// </summary>    
    [Table("jeecg_demo")]
    public class jeecg_demo : ObservableObject
    {
        private string _id;
        /// <summary>
        /// id
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _name;
        /// <summary>
        /// 名称
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private int? _age;
        /// <summary>
        /// 年龄
        /// </summary>
        public int? age
        {
            get { return _age; }
            set { updateProper(ref _age, value);}
        }
    
        private DateTime? _birthday;
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? birthday
        {
            get { return _birthday; }
            set { updateProper(ref _birthday, value);}
        }
    
        private string _content;
        /// <summary>
        /// 个人介绍
        /// </summary>
        public string content
        {
            get { return _content; }
            set { updateProper(ref _content, value);}
        }
    
        private string _dep_id;
        /// <summary>
        /// 部门
        /// </summary>
        public string dep_id
        {
            get { return _dep_id; }
            set { updateProper(ref _dep_id, value);}
        }
    
        private string _email;
        /// <summary>
        /// 邮箱
        /// </summary>
        public string email
        {
            get { return _email; }
            set { updateProper(ref _email, value);}
        }
    
        private string _phone;
        /// <summary>
        /// 电话
        /// </summary>
        public string phone
        {
            get { return _phone; }
            set { updateProper(ref _phone, value);}
        }
    
        private double? _salary;
        /// <summary>
        /// 工资
        /// </summary>
        public double? salary
        {
            get { return _salary; }
            set { updateProper(ref _salary, value);}
        }
    
        private string _sex;
        /// <summary>
        /// 性别
        /// </summary>
        public string sex
        {
            get { return _sex; }
            set { updateProper(ref _sex, value);}
        }
    
        private string _touxiang;
        /// <summary>
        /// 头像
        /// </summary>
        public string touxiang
        {
            get { return _touxiang; }
            set { updateProper(ref _touxiang, value);}
        }
    
        private string _fujian;
        /// <summary>
        /// 附件
        /// </summary>
        public string fujian
        {
            get { return _fujian; }
            set { updateProper(ref _fujian, value);}
        }
    
        private string _status;
        /// <summary>
        /// 入职状态
        /// </summary>
        public string status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// createDate
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人id
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 修改人id
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 部门编码
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 公司编码
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    }
}
