//-----------------------------------------------------------------------
// <copyright file=" jeecg_order_main.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_order_main.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jeecg_order_main Entity Model
    /// </summary>    
    [Table("jeecg_order_main")]
    public class jeecg_order_main : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// 
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private DateTime? _CREATE_DT;
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CREATE_DT
        {
            get { return _CREATE_DT; }
            set { updateProper(ref _CREATE_DT, value);}
        }
    
        private string _CRTUSER;
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER
        {
            get { return _CRTUSER; }
            set { updateProper(ref _CRTUSER, value);}
        }
    
        private string _CRTUSER_NAME;
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER_NAME
        {
            get { return _CRTUSER_NAME; }
            set { updateProper(ref _CRTUSER_NAME, value);}
        }
    
        private DateTime? _DEL_DT;
        /// <summary>
        /// 
        /// </summary>
        public DateTime? DEL_DT
        {
            get { return _DEL_DT; }
            set { updateProper(ref _DEL_DT, value);}
        }
    
        private int? _DELFLAG;
        /// <summary>
        /// 
        /// </summary>
        public int? DELFLAG
        {
            get { return _DELFLAG; }
            set { updateProper(ref _DELFLAG, value);}
        }
    
        private decimal? _GO_ALL_PRICE;
        /// <summary>
        /// 
        /// </summary>
        public decimal? GO_ALL_PRICE
        {
            get { return _GO_ALL_PRICE; }
            set { updateProper(ref _GO_ALL_PRICE, value);}
        }
    
        private string _GO_CONTACT_NAME;
        /// <summary>
        /// 
        /// </summary>
        public string GO_CONTACT_NAME
        {
            get { return _GO_CONTACT_NAME; }
            set { updateProper(ref _GO_CONTACT_NAME, value);}
        }
    
        private string _GO_CONTENT;
        /// <summary>
        /// 
        /// </summary>
        public string GO_CONTENT
        {
            get { return _GO_CONTENT; }
            set { updateProper(ref _GO_CONTENT, value);}
        }
    
        private string _GO_ORDER_CODE;
        /// <summary>
        /// 
        /// </summary>
        public string GO_ORDER_CODE
        {
            get { return _GO_ORDER_CODE; }
            set { updateProper(ref _GO_ORDER_CODE, value);}
        }
    
        private int? _GO_ORDER_COUNT;
        /// <summary>
        /// 
        /// </summary>
        public int? GO_ORDER_COUNT
        {
            get { return _GO_ORDER_COUNT; }
            set { updateProper(ref _GO_ORDER_COUNT, value);}
        }
    
        private decimal? _GO_RETURN_PRICE;
        /// <summary>
        /// 
        /// </summary>
        public decimal? GO_RETURN_PRICE
        {
            get { return _GO_RETURN_PRICE; }
            set { updateProper(ref _GO_RETURN_PRICE, value);}
        }
    
        private string _GO_TELPHONE;
        /// <summary>
        /// 
        /// </summary>
        public string GO_TELPHONE
        {
            get { return _GO_TELPHONE; }
            set { updateProper(ref _GO_TELPHONE, value);}
        }
    
        private string _GODER_TYPE;
        /// <summary>
        /// 
        /// </summary>
        public string GODER_TYPE
        {
            get { return _GODER_TYPE; }
            set { updateProper(ref _GODER_TYPE, value);}
        }
    
        private string _MODIFIER;
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER
        {
            get { return _MODIFIER; }
            set { updateProper(ref _MODIFIER, value);}
        }
    
        private string _MODIFIER_NAME;
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER_NAME
        {
            get { return _MODIFIER_NAME; }
            set { updateProper(ref _MODIFIER_NAME, value);}
        }
    
        private DateTime? _MODIFY_DT;
        /// <summary>
        /// 
        /// </summary>
        public DateTime? MODIFY_DT
        {
            get { return _MODIFY_DT; }
            set { updateProper(ref _MODIFY_DT, value);}
        }
    
        private string _USERTYPE;
        /// <summary>
        /// 
        /// </summary>
        public string USERTYPE
        {
            get { return _USERTYPE; }
            set { updateProper(ref _USERTYPE, value);}
        }
    }
}
