//-----------------------------------------------------------------------
// <copyright file=" jeecg_custom_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_custom_info.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// jeecg_custom_info Entity Model
    /// </summary>    
    [Table("jeecg_custom_info")]
    public class jeecg_custom_info
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 客户名称
        /// </summary>
        public string cust_name { get; set; }
    
        /// <summary>
        /// 地址
        /// </summary>
        public string cust_addr { get; set; }
    
        /// <summary>
        /// 客户编号
        /// </summary>
        public string cust_code { get; set; }
    
        /// <summary>
        /// email
        /// </summary>
        public string email { get; set; }
    
        /// <summary>
        /// 负责人
        /// </summary>
        public string cust_charge { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        public string sex { get; set; }
    
        /// <summary>
        /// 年龄
        /// </summary>
        public string age { get; set; }
    
        /// <summary>
        /// 职务
        /// </summary>
        public string position { get; set; }
    
        /// <summary>
        /// 电话
        /// </summary>
        public string phone { get; set; }
    
        /// <summary>
        /// 往来银行
        /// </summary>
        public string bank { get; set; }
    
        /// <summary>
        /// 现金情况
        /// </summary>
        public string money { get; set; }
    
        /// <summary>
        /// 承办人
        /// </summary>
        public string promoter { get; set; }
    
        /// <summary>
        /// 账号
        /// </summary>
        public string account { get; set; }
    
        /// <summary>
        /// 资金周转
        /// </summary>
        public string turnover { get; set; }
    
        /// <summary>
        /// 付款态度
        /// </summary>
        public string payment_attr { get; set; }
    
        /// <summary>
        /// 税号
        /// </summary>
        public string sax_num { get; set; }
    
        /// <summary>
        /// 付款日期
        /// </summary>
        public string pay_date { get; set; }
    
        /// <summary>
        /// 开始交易日期
        /// </summary>
        public string begin_pay_date { get; set; }
    
        /// <summary>
        /// 主营产品
        /// </summary>
        public string main_bus { get; set; }
    
        /// <summary>
        /// 营业项目
        /// </summary>
        public string bus_pro { get; set; }
    
        /// <summary>
        /// 仓库情况
        /// </summary>
        public string warehouse { get; set; }
    
        /// <summary>
        /// 员工人数及素质
        /// </summary>
        public string people { get; set; }
    
        /// <summary>
        /// 运输方式
        /// </summary>
        public string transportation { get; set; }
    
        /// <summary>
        /// 经营体制
        /// </summary>
        public string operation { get; set; }
    
        /// <summary>
        /// 服务车数目
        /// </summary>
        public string car { get; set; }
    
        /// <summary>
        /// 零售商数及覆盖情况
        /// </summary>
        public string shopkeeper { get; set; }
    
        /// <summary>
        /// 批发商数
        /// </summary>
        public string wholesale { get; set; }
    
        /// <summary>
        /// 营业范围
        /// </summary>
        public string bus_scope { get; set; }
    
        /// <summary>
        /// 门市面积
        /// </summary>
        public string area { get; set; }
    
        /// <summary>
        /// 经营方针
        /// </summary>
        public string management { get; set; }
    
        /// <summary>
        /// 进货
        /// </summary>
        public string stock1 { get; set; }
    
        /// <summary>
        /// 进货
        /// </summary>
        public string stock2 { get; set; }
    
        /// <summary>
        /// 销售
        /// </summary>
        public string sale1 { get; set; }
    
        /// <summary>
        /// 销售
        /// </summary>
        public string sale2 { get; set; }
    
        /// <summary>
        /// 存货
        /// </summary>
        public string inventory1 { get; set; }
    
        /// <summary>
        /// 存货
        /// </summary>
        public string inventory2 { get; set; }
    
        /// <summary>
        /// 最高信用额度
        /// </summary>
        public string max_money { get; set; }
    
        /// <summary>
        /// 客户等级
        /// </summary>
        public string cust_level { get; set; }
    
        /// <summary>
        /// 总体月均库存数
        /// </summary>
        public string all_avg_inventory { get; set; }
    
        /// <summary>
        /// 月均库存数
        /// </summary>
        public string avg_inventory { get; set; }
    
        /// <summary>
        /// 价格折扣
        /// </summary>
        public string price { get; set; }
    
        /// <summary>
        /// 支持和服务的承诺
        /// </summary>
        public string promise { get; set; }
    
        /// <summary>
        /// 竞品经营情况
        /// </summary>
        public string competing_goods { get; set; }
    }
}
