//-----------------------------------------------------------------------
// <copyright file=" jeecg_demo.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_demo.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jeecg_demo Entity Model
    /// </summary>    
export class jeecg_demo
{
        /// <summary>
        /// id
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 名称
        /// </summary>
    public name:string;
    
        /// <summary>
        /// 年龄
        /// </summary>
    public age:number;
    
        /// <summary>
        /// 生日
        /// </summary>
    public birthday:Date;
    
        /// <summary>
        /// 个人介绍
        /// </summary>
    public content:string;
    
        /// <summary>
        /// 部门
        /// </summary>
    public dep_id:string;
    
        /// <summary>
        /// 邮箱
        /// </summary>
    public email:string;
    
        /// <summary>
        /// 电话
        /// </summary>
    public phone:string;
    
        /// <summary>
        /// 工资
        /// </summary>
    public salary:number;
    
        /// <summary>
        /// 性别
        /// </summary>
    public sex:string;
    
        /// <summary>
        /// 头像
        /// </summary>
    public touxiang:string;
    
        /// <summary>
        /// 附件
        /// </summary>
    public fujian:string;
    
        /// <summary>
        /// 入职状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// createDate
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 创建人id
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建人
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 修改人id
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 修改时间
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 修改人
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 部门编码
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 公司编码
        /// </summary>
    public sys_company_code:string;
}

