//-----------------------------------------------------------------------
// <copyright file=" jeecg_order_main.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_order_main.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jeecg_order_main Entity Model
    /// </summary>    
export class jeecg_order_main
{
        /// <summary>
        /// 
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 
        /// </summary>
    public CREATE_DT:Date;
    
        /// <summary>
        /// 
        /// </summary>
    public CRTUSER:string;
    
        /// <summary>
        /// 
        /// </summary>
    public CRTUSER_NAME:string;
    
        /// <summary>
        /// 
        /// </summary>
    public DEL_DT:Date;
    
        /// <summary>
        /// 
        /// </summary>
    public DELFLAG:number;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_ALL_PRICE:number;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_CONTACT_NAME:string;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_CONTENT:string;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_ORDER_CODE:string;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_ORDER_COUNT:number;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_RETURN_PRICE:number;
    
        /// <summary>
        /// 
        /// </summary>
    public GO_TELPHONE:string;
    
        /// <summary>
        /// 
        /// </summary>
    public GODER_TYPE:string;
    
        /// <summary>
        /// 
        /// </summary>
    public MODIFIER:string;
    
        /// <summary>
        /// 
        /// </summary>
    public MODIFIER_NAME:string;
    
        /// <summary>
        /// 
        /// </summary>
    public MODIFY_DT:Date;
    
        /// <summary>
        /// 
        /// </summary>
    public USERTYPE:string;
}

