//-----------------------------------------------------------------------
// <copyright file=" jeecg_order_main.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jeecg_order_main.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jeecg_order_main Entity Model
    /// </summary>    
    [Serializable]
    public class jeecg_order_main
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime CREATE_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime DEL_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int DELFLAG { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public decimal GO_ALL_PRICE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GO_CONTACT_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GO_CONTENT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GO_ORDER_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int GO_ORDER_COUNT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public decimal GO_RETURN_PRICE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GO_TELPHONE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string GODER_TYPE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime MODIFY_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string USERTYPE { get; set; }
    }
}
