//-----------------------------------------------------------------------
// <copyright file=" jform_employee_resignation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_employee_resignation.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// jform_employee_resignation Entity Model
    /// </summary>    
    [Table("jform_employee_resignation")]
    public class jform_employee_resignation
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 姓名
        /// </summary>
        public string name { get; set; }
    
        /// <summary>
        /// 员工编号
        /// </summary>
        public string code { get; set; }
    
        /// <summary>
        /// 职务
        /// </summary>
        public string job { get; set; }
    
        /// <summary>
        /// 入职时间
        /// </summary>
        public DateTime? join_time { get; set; }
    
        /// <summary>
        /// 离职方式
        /// </summary>
        public string out_type { get; set; }
    
        /// <summary>
        /// 申请离职日期
        /// </summary>
        public DateTime? apply_out_time { get; set; }
    
        /// <summary>
        /// 正式离职日期
        /// </summary>
        public DateTime? out_time { get; set; }
    
        /// <summary>
        /// 身份证编号
        /// </summary>
        public string id_card { get; set; }
    
        /// <summary>
        /// 离职须知
        /// </summary>
        public string out_content { get; set; }
    
        /// <summary>
        /// 离职原因
        /// </summary>
        public string out_reason { get; set; }
    
        /// <summary>
        /// 面谈记录
        /// </summary>
        public string interview_record { get; set; }
    
        /// <summary>
        /// 办公物品移交
        /// </summary>
        public string office_change { get; set; }
    
        /// <summary>
        /// 人力资源部审核
        /// </summary>
        public string hr_check { get; set; }
    
        /// <summary>
        /// 应发薪资
        /// </summary>
        public double? should_send_salary { get; set; }
    
        /// <summary>
        /// 应扣薪资
        /// </summary>
        public double? should_deduct_pay { get; set; }
    
        /// <summary>
        /// 实发薪资
        /// </summary>
        public double? pay { get; set; }
    
        /// <summary>
        /// 领取日期
        /// </summary>
        public DateTime? get_time { get; set; }
    
        /// <summary>
        /// 总经理审批
        /// </summary>
        public string boss_check { get; set; }
    
        /// <summary>
        /// 说明
        /// </summary>
        public string description { get; set; }
    }
}
