//-----------------------------------------------------------------------
// <copyright file=" jform_leave.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_leave.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_leave Entity Model
    /// </summary>    
    [Table("jform_leave")]
    public class jform_leave : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _title;
        /// <summary>
        /// 请假标题
        /// </summary>
        public string title
        {
            get { return _title; }
            set { updateProper(ref _title, value);}
        }
    
        private string _people;
        /// <summary>
        /// 请假人
        /// </summary>
        public string people
        {
            get { return _people; }
            set { updateProper(ref _people, value);}
        }
    
        private string _sex;
        /// <summary>
        /// 性别
        /// </summary>
        public string sex
        {
            get { return _sex; }
            set { updateProper(ref _sex, value);}
        }
    
        private DateTime? _begindate;
        /// <summary>
        /// 请假开始时间
        /// </summary>
        public DateTime? begindate
        {
            get { return _begindate; }
            set { updateProper(ref _begindate, value);}
        }
    
        private DateTime? _enddate;
        /// <summary>
        /// 请假结束时间
        /// </summary>
        public DateTime? enddate
        {
            get { return _enddate; }
            set { updateProper(ref _enddate, value);}
        }
    
        private int? _day_num;
        /// <summary>
        /// 请假天数
        /// </summary>
        public int? day_num
        {
            get { return _day_num; }
            set { updateProper(ref _day_num, value);}
        }
    
        private string _hol_dept;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string hol_dept
        {
            get { return _hol_dept; }
            set { updateProper(ref _hol_dept, value);}
        }
    
        private string _hol_reson;
        /// <summary>
        /// 请假原因
        /// </summary>
        public string hol_reson
        {
            get { return _hol_reson; }
            set { updateProper(ref _hol_reson, value);}
        }
    
        private string _dep_leader;
        /// <summary>
        /// 部门审批人
        /// </summary>
        public string dep_leader
        {
            get { return _dep_leader; }
            set { updateProper(ref _dep_leader, value);}
        }
    
        private string _content;
        /// <summary>
        /// 部门审批意见
        /// </summary>
        public string content
        {
            get { return _content; }
            set { updateProper(ref _content, value);}
        }
    
        private string _file_str;
        /// <summary>
        /// 附件
        /// </summary>
        public string file_str
        {
            get { return _file_str; }
            set { updateProper(ref _file_str, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    }
}
