//-----------------------------------------------------------------------
// <copyright file=" jform_order_ticket.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_order_ticket.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jform_order_ticket Entity Model
    /// </summary>    
    [Serializable]
    public class jform_order_ticket
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 航班号
        /// </summary>
        public string ticket_code { get; set; }
    
        /// <summary>
        /// 航班时间
        /// </summary>
        public DateTime tickect_date { get; set; }
    
        /// <summary>
        /// 外键
        /// </summary>
        public string fck_id { get; set; }
    }
}
