//-----------------------------------------------------------------------
// <copyright file=" jform_order_main.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_order_main.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// jform_order_main Entity Model
    /// </summary>    
    [Table("jform_order_main")]
    public class jform_order_main
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 订单号
        /// </summary>
        public string order_code { get; set; }
    
        /// <summary>
        /// 订单日期
        /// </summary>
        public DateTime? order_date { get; set; }
    
        /// <summary>
        /// 订单金额
        /// </summary>
        public double? order_money { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string content { get; set; }
    
        /// <summary>
        /// 订单扫描件
        /// </summary>
        public string ctype { get; set; }
    }
}
