//-----------------------------------------------------------------------
// <copyright file=" jform_leave.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_leave.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jform_leave Entity Model
    /// </summary>    
    [Serializable]
    public class jform_leave
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 请假标题
        /// </summary>
        public string title { get; set; }
    
        /// <summary>
        /// 请假人
        /// </summary>
        public string people { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        public string sex { get; set; }
    
        /// <summary>
        /// 请假开始时间
        /// </summary>
        public DateTime begindate { get; set; }
    
        /// <summary>
        /// 请假结束时间
        /// </summary>
        public DateTime enddate { get; set; }
    
        /// <summary>
        /// 请假天数
        /// </summary>
        public int day_num { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string hol_dept { get; set; }
    
        /// <summary>
        /// 请假原因
        /// </summary>
        public string hol_reson { get; set; }
    
        /// <summary>
        /// 部门审批人
        /// </summary>
        public string dep_leader { get; set; }
    
        /// <summary>
        /// 部门审批意见
        /// </summary>
        public string content { get; set; }
    
        /// <summary>
        /// 附件
        /// </summary>
        public string file_str { get; set; }
    
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_by { get; set; }
    }
}
