//-----------------------------------------------------------------------
// <copyright file=" jform_employee_leave.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_employee_leave.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_employee_leave Entity Model
    /// </summary>    
    [Table("jform_employee_leave")]
    public class jform_employee_leave : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _name;
        /// <summary>
        /// 名称
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private DateTime? _apply_date;
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime? apply_date
        {
            get { return _apply_date; }
            set { updateProper(ref _apply_date, value);}
        }
    
        private string _duty;
        /// <summary>
        /// 职务
        /// </summary>
        public string duty
        {
            get { return _duty; }
            set { updateProper(ref _duty, value);}
        }
    
        private string _leave_category;
        /// <summary>
        /// 请假类别
        /// </summary>
        public string leave_category
        {
            get { return _leave_category; }
            set { updateProper(ref _leave_category, value);}
        }
    
        private string _leave_reason;
        /// <summary>
        /// 请假原因
        /// </summary>
        public string leave_reason
        {
            get { return _leave_reason; }
            set { updateProper(ref _leave_reason, value);}
        }
    
        private DateTime? _leave_start_date;
        /// <summary>
        /// 请假开始时间
        /// </summary>
        public DateTime? leave_start_date
        {
            get { return _leave_start_date; }
            set { updateProper(ref _leave_start_date, value);}
        }
    
        private DateTime? _leave_end_date;
        /// <summary>
        /// 请假结束时间
        /// </summary>
        public DateTime? leave_end_date
        {
            get { return _leave_end_date; }
            set { updateProper(ref _leave_end_date, value);}
        }
    
        private int? _total;
        /// <summary>
        /// 共计
        /// </summary>
        public int? total
        {
            get { return _total; }
            set { updateProper(ref _total, value);}
        }
    
        private string _contact_way;
        /// <summary>
        /// 紧急联系方式
        /// </summary>
        public string contact_way
        {
            get { return _contact_way; }
            set { updateProper(ref _contact_way, value);}
        }
    
        private string _duty_deputy;
        /// <summary>
        /// 批定职务代理人
        /// </summary>
        public string duty_deputy
        {
            get { return _duty_deputy; }
            set { updateProper(ref _duty_deputy, value);}
        }
    
        private string _leader_approval;
        /// <summary>
        /// 直接主管审批
        /// </summary>
        public string leader_approval
        {
            get { return _leader_approval; }
            set { updateProper(ref _leader_approval, value);}
        }
    
        private string _dept_principal_approval;
        /// <summary>
        /// 部门负责人审批
        /// </summary>
        public string dept_principal_approval
        {
            get { return _dept_principal_approval; }
            set { updateProper(ref _dept_principal_approval, value);}
        }
    
        private string _hr_principal_approval;
        /// <summary>
        /// HR负责人审批
        /// </summary>
        public string hr_principal_approval
        {
            get { return _hr_principal_approval; }
            set { updateProper(ref _hr_principal_approval, value);}
        }
    
        private string _hr_records;
        /// <summary>
        /// 行政部备案
        /// </summary>
        public string hr_records
        {
            get { return _hr_records; }
            set { updateProper(ref _hr_records, value);}
        }
    
        private string _department;
        /// <summary>
        /// 部门
        /// </summary>
        public string department
        {
            get { return _department; }
            set { updateProper(ref _department, value);}
        }
    }
}
