//-----------------------------------------------------------------------
// <copyright file=" jform_contact.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_contact.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_contact Entity Model
    /// </summary>    
    [Table("jform_contact")]
    public class jform_contact : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _name;
        /// <summary>
        /// 姓名
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private string _sex;
        /// <summary>
        /// 性别
        /// </summary>
        public string sex
        {
            get { return _sex; }
            set { updateProper(ref _sex, value);}
        }
    
        private string _groups;
        /// <summary>
        /// 所属分组
        /// </summary>
        public string groups
        {
            get { return _groups; }
            set { updateProper(ref _groups, value);}
        }
    
        private string _company;
        /// <summary>
        /// 公司名称
        /// </summary>
        public string company
        {
            get { return _company; }
            set { updateProper(ref _company, value);}
        }
    
        private string _position;
        /// <summary>
        /// 职位
        /// </summary>
        public string position
        {
            get { return _position; }
            set { updateProper(ref _position, value);}
        }
    
        private string _mobile;
        /// <summary>
        /// 移动电话
        /// </summary>
        public string mobile
        {
            get { return _mobile; }
            set { updateProper(ref _mobile, value);}
        }
    
        private string _office_phone;
        /// <summary>
        /// 办公电话
        /// </summary>
        public string office_phone
        {
            get { return _office_phone; }
            set { updateProper(ref _office_phone, value);}
        }
    
        private string _email;
        /// <summary>
        /// 电子邮箱
        /// </summary>
        public string email
        {
            get { return _email; }
            set { updateProper(ref _email, value);}
        }
    }
}
