//-----------------------------------------------------------------------
// <copyright file=" jform_cgdynamgraph_param.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_cgdynamgraph_param.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// jform_cgdynamgraph_param Entity Model
    /// </summary>    
    [Table("jform_cgdynamgraph_param")]
    public class jform_cgdynamgraph_param
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 参数名称
        /// </summary>
        public string param_name { get; set; }
    
        /// <summary>
        /// 参数说明
        /// </summary>
        public string param_desc { get; set; }
    
        /// <summary>
        /// 数值
        /// </summary>
        public string param_value { get; set; }
    
        /// <summary>
        /// 排序
        /// </summary>
        public int? seq { get; set; }
    
        /// <summary>
        /// 动态报表ID
        /// </summary>
        public string cgrhead_id { get; set; }
    }
}
