//-----------------------------------------------------------------------
// <copyright file=" jform_employee_resignation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_employee_resignation.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_employee_resignation Entity Model
    /// </summary>    
    [Table("jform_employee_resignation")]
    public class jform_employee_resignation : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _name;
        /// <summary>
        /// 姓名
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private string _code;
        /// <summary>
        /// 员工编号
        /// </summary>
        public string code
        {
            get { return _code; }
            set { updateProper(ref _code, value);}
        }
    
        private string _job;
        /// <summary>
        /// 职务
        /// </summary>
        public string job
        {
            get { return _job; }
            set { updateProper(ref _job, value);}
        }
    
        private DateTime? _join_time;
        /// <summary>
        /// 入职时间
        /// </summary>
        public DateTime? join_time
        {
            get { return _join_time; }
            set { updateProper(ref _join_time, value);}
        }
    
        private string _out_type;
        /// <summary>
        /// 离职方式
        /// </summary>
        public string out_type
        {
            get { return _out_type; }
            set { updateProper(ref _out_type, value);}
        }
    
        private DateTime? _apply_out_time;
        /// <summary>
        /// 申请离职日期
        /// </summary>
        public DateTime? apply_out_time
        {
            get { return _apply_out_time; }
            set { updateProper(ref _apply_out_time, value);}
        }
    
        private DateTime? _out_time;
        /// <summary>
        /// 正式离职日期
        /// </summary>
        public DateTime? out_time
        {
            get { return _out_time; }
            set { updateProper(ref _out_time, value);}
        }
    
        private string _id_card;
        /// <summary>
        /// 身份证编号
        /// </summary>
        public string id_card
        {
            get { return _id_card; }
            set { updateProper(ref _id_card, value);}
        }
    
        private string _out_content;
        /// <summary>
        /// 离职须知
        /// </summary>
        public string out_content
        {
            get { return _out_content; }
            set { updateProper(ref _out_content, value);}
        }
    
        private string _out_reason;
        /// <summary>
        /// 离职原因
        /// </summary>
        public string out_reason
        {
            get { return _out_reason; }
            set { updateProper(ref _out_reason, value);}
        }
    
        private string _interview_record;
        /// <summary>
        /// 面谈记录
        /// </summary>
        public string interview_record
        {
            get { return _interview_record; }
            set { updateProper(ref _interview_record, value);}
        }
    
        private string _office_change;
        /// <summary>
        /// 办公物品移交
        /// </summary>
        public string office_change
        {
            get { return _office_change; }
            set { updateProper(ref _office_change, value);}
        }
    
        private string _hr_check;
        /// <summary>
        /// 人力资源部审核
        /// </summary>
        public string hr_check
        {
            get { return _hr_check; }
            set { updateProper(ref _hr_check, value);}
        }
    
        private double? _should_send_salary;
        /// <summary>
        /// 应发薪资
        /// </summary>
        public double? should_send_salary
        {
            get { return _should_send_salary; }
            set { updateProper(ref _should_send_salary, value);}
        }
    
        private double? _should_deduct_pay;
        /// <summary>
        /// 应扣薪资
        /// </summary>
        public double? should_deduct_pay
        {
            get { return _should_deduct_pay; }
            set { updateProper(ref _should_deduct_pay, value);}
        }
    
        private double? _pay;
        /// <summary>
        /// 实发薪资
        /// </summary>
        public double? pay
        {
            get { return _pay; }
            set { updateProper(ref _pay, value);}
        }
    
        private DateTime? _get_time;
        /// <summary>
        /// 领取日期
        /// </summary>
        public DateTime? get_time
        {
            get { return _get_time; }
            set { updateProper(ref _get_time, value);}
        }
    
        private string _boss_check;
        /// <summary>
        /// 总经理审批
        /// </summary>
        public string boss_check
        {
            get { return _boss_check; }
            set { updateProper(ref _boss_check, value);}
        }
    
        private string _description;
        /// <summary>
        /// 说明
        /// </summary>
        public string description
        {
            get { return _description; }
            set { updateProper(ref _description, value);}
        }
    }
}
