//-----------------------------------------------------------------------
// <copyright file=" jform_order_customer.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_order_customer.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jform_order_customer Entity Model
    /// </summary>    
export class jform_order_customer
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 客户名
        /// </summary>
    public name:string;
    
        /// <summary>
        /// 单价
        /// </summary>
    public money:number;
    
        /// <summary>
        /// 性别
        /// </summary>
    public sex:string;
    
        /// <summary>
        /// 电话
        /// </summary>
    public telphone:string;
    
        /// <summary>
        /// 外键
        /// </summary>
    public fk_id:string;
    
        /// <summary>
        /// 身份证扫描件
        /// </summary>
    public sf_pic:string;
}

