//-----------------------------------------------------------------------
// <copyright file=" jform_graphreport_head.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_graphreport_head.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_graphreport_head Entity Model
    /// </summary>    
    [Table("jform_graphreport_head")]
    public class jform_graphreport_head : ObservableObject
    {
        private string _id;
        /// <summary>
        /// id
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _cgr_sql;
        /// <summary>
        /// 查询数据SQL
        /// </summary>
        public string cgr_sql
        {
            get { return _cgr_sql; }
            set { updateProper(ref _cgr_sql, value);}
        }
    
        private string _code;
        /// <summary>
        /// 编码
        /// </summary>
        public string code
        {
            get { return _code; }
            set { updateProper(ref _code, value);}
        }
    
        private string _content;
        /// <summary>
        /// 描述
        /// </summary>
        public string content
        {
            get { return _content; }
            set { updateProper(ref _content, value);}
        }
    
        private string _name;
        /// <summary>
        /// 名称
        /// </summary>
        public string name
        {
            get { return _name; }
            set { updateProper(ref _name, value);}
        }
    
        private string _ytext;
        /// <summary>
        /// y轴文字
        /// </summary>
        public string ytext
        {
            get { return _ytext; }
            set { updateProper(ref _ytext, value);}
        }
    
        private string _categories;
        /// <summary>
        /// x轴数据
        /// </summary>
        public string categories
        {
            get { return _categories; }
            set { updateProper(ref _categories, value);}
        }
    
        private string _is_show_list;
        /// <summary>
        /// 是否显示明细
        /// </summary>
        public string is_show_list
        {
            get { return _is_show_list; }
            set { updateProper(ref _is_show_list, value);}
        }
    
        private string _x_page_js;
        /// <summary>
        /// 扩展JS
        /// </summary>
        public string x_page_js
        {
            get { return _x_page_js; }
            set { updateProper(ref _x_page_js, value);}
        }
    }
}
