//-----------------------------------------------------------------------
// <copyright file=" jform_cgdynamgraph_head.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_cgdynamgraph_head.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jform_cgdynamgraph_head Entity Model
    /// </summary>    
    [Table("jform_cgdynamgraph_head")]
    public class jform_cgdynamgraph_head : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// 主键ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _CGR_SQL;
        /// <summary>
        /// 移动报表SQL
        /// </summary>
        public string CGR_SQL
        {
            get { return _CGR_SQL; }
            set { updateProper(ref _CGR_SQL, value);}
        }
    
        private string _CODE;
        /// <summary>
        /// 移动报表编码
        /// </summary>
        public string CODE
        {
            get { return _CODE; }
            set { updateProper(ref _CODE, value);}
        }
    
        private string _CONTENT;
        /// <summary>
        /// 描述
        /// </summary>
        public string CONTENT
        {
            get { return _CONTENT; }
            set { updateProper(ref _CONTENT, value);}
        }
    
        private string _NAME;
        /// <summary>
        /// 移动报表名字
        /// </summary>
        public string NAME
        {
            get { return _NAME; }
            set { updateProper(ref _NAME, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 修改人id
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人id
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private string _db_source;
        /// <summary>
        /// 动态数据源
        /// </summary>
        public string db_source
        {
            get { return _db_source; }
            set { updateProper(ref _db_source, value);}
        }
    
        private string _graph_type;
        /// <summary>
        /// 移动报表类型
        /// </summary>
        public string graph_type
        {
            get { return _graph_type; }
            set { updateProper(ref _graph_type, value);}
        }
    
        private string _data_structure;
        /// <summary>
        /// 数据结构类型
        /// </summary>
        public string data_structure
        {
            get { return _data_structure; }
            set { updateProper(ref _data_structure, value);}
        }
    
        private string _is_pagination;
        /// <summary>
        /// 
        /// </summary>
        public string is_pagination
        {
            get { return _is_pagination; }
            set { updateProper(ref _is_pagination, value);}
        }
    }
}
