//-----------------------------------------------------------------------
// <copyright file=" jform_resume_degree_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_resume_degree_info.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jform_resume_degree_info Entity Model
    /// </summary>    
    [Serializable]
    public class jform_resume_degree_info
    {
        /// <summary>
        /// id
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 简历主键
        /// </summary>
        public string resume_id { get; set; }
    
        /// <summary>
        /// 开始时间
        /// </summary>
        public DateTime begin_date { get; set; }
    
        /// <summary>
        /// 结束时间
        /// </summary>
        public DateTime end_date { get; set; }
    
        /// <summary>
        /// 学校名称
        /// </summary>
        public string school_name { get; set; }
    
        /// <summary>
        /// 专业
        /// </summary>
        public string major { get; set; }
    
        /// <summary>
        /// 学历
        /// </summary>
        public string degree { get; set; }
    }
}
