//-----------------------------------------------------------------------
// <copyright file=" jform_employee_meals_cost.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_employee_meals_cost.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// jform_employee_meals_cost Entity Model
    /// </summary>    
    [Table("jform_employee_meals_cost")]
    public class jform_employee_meals_cost
    {
        /// <summary>
        /// id
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 外键
        /// </summary>
        public string fk_id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? meals_date { get; set; }
    
        /// <summary>
        /// 餐费
        /// </summary>
        public decimal? meals_cost { get; set; }
    
        /// <summary>
        /// 吃饭地点
        /// </summary>
        public string meals_addr { get; set; }
    
        /// <summary>
        /// 同行人数
        /// </summary>
        public int? meals_number { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string comments { get; set; }
    }
}
