//-----------------------------------------------------------------------
// <copyright file=" jform_employee_entry.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_employee_entry.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jform_employee_entry Entity Model
    /// </summary>    
export class jform_employee_entry
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 填表日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 姓名
        /// </summary>
    public employee_name:string;
    
        /// <summary>
        /// 部门
        /// </summary>
    public employee_depart:string;
    
        /// <summary>
        /// 职务
        /// </summary>
    public employee_job:string;
    
        /// <summary>
        /// 生日
        /// </summary>
    public employee_birthday:Date;
    
        /// <summary>
        /// 籍贯
        /// </summary>
    public employee_origin:string;
    
        /// <summary>
        /// 学历
        /// </summary>
    public employee_degree:string;
    
        /// <summary>
        /// 身份证
        /// </summary>
    public employee_identification:string;
    
        /// <summary>
        /// 入职日期
        /// </summary>
    public employee_entry_date:Date;
    
        /// <summary>
        /// 工号
        /// </summary>
    public employee_code:string;
    
        /// <summary>
        /// 手机
        /// </summary>
    public employee_phone:string;
    
        /// <summary>
        /// 邮箱
        /// </summary>
    public employee_mail:string;
    
        /// <summary>
        /// MSN
        /// </summary>
    public employee_msn:string;
    
        /// <summary>
        /// 照片
        /// </summary>
    public hr_pic:string;
    
        /// <summary>
        /// 档案表
        /// </summary>
    public hr_archives:string;
    
        /// <summary>
        /// 身份证
        /// </summary>
    public hr_identification:string;
    
        /// <summary>
        /// 学位证
        /// </summary>
    public hr_degree:string;
    
        /// <summary>
        /// 其他证件
        /// </summary>
    public hr_other:string;
    
        /// <summary>
        /// 分配电话
        /// </summary>
    public hr_tel:string;
    
        /// <summary>
        /// 经办人
        /// </summary>
    public hr_op_user:string;
    
        /// <summary>
        /// 日期
        /// </summary>
    public hr_op_date:Date;
    
        /// <summary>
        /// 部门意见
        /// </summary>
    public depart_opinion:string;
    
        /// <summary>
        /// 经办人
        /// </summary>
    public depart_op_user:string;
    
        /// <summary>
        /// 日期
        /// </summary>
    public depart_op_date:Date;
    
        /// <summary>
        /// 总经理意见
        /// </summary>
    public manager_opinion:string;
    
        /// <summary>
        /// 经办人
        /// </summary>
    public manager_op_user:string;
    
        /// <summary>
        /// 日期
        /// </summary>
    public manager_op_date:Date;
    
        /// <summary>
        /// 新员工意见
        /// </summary>
    public employee_opinion:string;
    
        /// <summary>
        /// 经办人
        /// </summary>
    public employee_op_user:string;
    
        /// <summary>
        /// 日期
        /// </summary>
    public employee_op_date:Date;
}

