//-----------------------------------------------------------------------
// <copyright file=" jform_resume_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_resume_info.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jform_resume_info Entity Model
    /// </summary>    
export class jform_resume_info
{
        /// <summary>
        /// id
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 姓名
        /// </summary>
    public name:string;
    
        /// <summary>
        /// 性别
        /// </summary>
    public sex:string;
    
        /// <summary>
        /// 生日
        /// </summary>
    public birthday:Date;
    
        /// <summary>
        /// 电话号码
        /// </summary>
    public telnum:string;
    
        /// <summary>
        /// 电子邮箱
        /// </summary>
    public email:string;
    
        /// <summary>
        /// 最高学历
        /// </summary>
    public degree:string;
    
        /// <summary>
        /// 工作年限
        /// </summary>
    public workyear:string;
    
        /// <summary>
        /// 身份证号
        /// </summary>
    public cardid:string;
    
        /// <summary>
        /// 现居地
        /// </summary>
    public habitation:string;
    
        /// <summary>
        /// 户口所在地
        /// </summary>
    public residence:string;
    
        /// <summary>
        /// 期望薪资
        /// </summary>
    public salary:string;
    
        /// <summary>
        /// 期望工作地点
        /// </summary>
    public work_place:string;
    
        /// <summary>
        /// 工作类型
        /// </summary>
    public work_type:string;
    
        /// <summary>
        /// 到岗时间
        /// </summary>
    public arrival_time:Date;
    
        /// <summary>
        /// 自我评价
        /// </summary>
    public introduction:string;
}

