//-----------------------------------------------------------------------
// <copyright file=" jform_cgreport_param.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jform_cgreport_param.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jform_cgreport_param Entity Model
    /// </summary>    
export class jform_cgreport_param
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 参数名称
        /// </summary>
    public param_name:string;
    
        /// <summary>
        /// 参数说明
        /// </summary>
    public param_desc:string;
    
        /// <summary>
        /// 数值
        /// </summary>
    public param_value:string;
    
        /// <summary>
        /// 排序
        /// </summary>
    public seq:number;
    
        /// <summary>
        /// 动态报表ID
        /// </summary>
    public cgrhead_id:string;
}

