//-----------------------------------------------------------------------
// <copyright file=" jp_chat_message_his.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_chat_message_his.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jp_chat_message_his Entity Model
    /// </summary>    
export class jp_chat_message_his
{
        /// <summary>
        /// 
        /// </summary>
    public id:number;
    
        /// <summary>
        /// 
        /// </summary>
    public msg_from:string;
    
        /// <summary>
        /// 
        /// </summary>
    public msg_to:string;
    
        /// <summary>
        /// 
        /// </summary>
    public msg_data:string;
    
        /// <summary>
        /// 
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 
        /// </summary>
    public type:string;
}

