//-----------------------------------------------------------------------
// <copyright file=" jp_chat_message_his.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_chat_message_his.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jp_chat_message_his Entity Model
    /// </summary>    
    [Serializable]
    public class jp_chat_message_his
    {
        /// <summary>
        /// 
        /// </summary>
        public int id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string msg_from { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string msg_to { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string msg_data { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime create_date { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string type { get; set; }
    }
}
