//-----------------------------------------------------------------------
// <copyright file=" jp_demo_order_custom.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_demo_order_custom.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jp_demo_order_custom Entity Model
    /// </summary>    
    [Serializable]
    public class jp_demo_order_custom
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime CREATE_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime DEL_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int DELFLAG { get; set; }
    
        /// <summary>
        /// 团购订单号
        /// </summary>
        public string GO_ORDER_CODE { get; set; }
    
        /// <summary>
        /// 业务
        /// </summary>
        public string GOC_BUSS_CONTENT { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string GOC_CONTENT { get; set; }
    
        /// <summary>
        /// 姓名
        /// </summary>
        public string GOC_CUS_NAME { get; set; }
    
        /// <summary>
        /// 身份证号
        /// </summary>
        public string GOC_IDCARD { get; set; }
    
        /// <summary>
        /// 护照号
        /// </summary>
        public string GOC_PASSPORT_CODE { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        public string GOC_SEX { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime MODIFY_DT { get; set; }
    }
}
