//-----------------------------------------------------------------------
// <copyright file=" jp_demo_order_main.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_demo_order_main.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// jp_demo_order_main Entity Model
    /// </summary>    
    [Table("jp_demo_order_main")]
    public class jp_demo_order_main
    {
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CREATE_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string CRTUSER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? DEL_DT { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int? DELFLAG { get; set; }
    
        /// <summary>
        /// 总价(不含返款)
        /// </summary>
        public decimal? GO_ALL_PRICE { get; set; }
    
        /// <summary>
        /// 联系人
        /// </summary>
        public string GO_CONTACT_NAME { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string GO_CONTENT { get; set; }
    
        /// <summary>
        /// 订单号
        /// </summary>
        public string GO_ORDER_CODE { get; set; }
    
        /// <summary>
        /// 订单人数
        /// </summary>
        public int? GO_ORDER_COUNT { get; set; }
    
        /// <summary>
        /// 返款
        /// </summary>
        public decimal? GO_RETURN_PRICE { get; set; }
    
        /// <summary>
        /// 手机
        /// </summary>
        public string GO_TELPHONE { get; set; }
    
        /// <summary>
        /// 订单类型
        /// </summary>
        public string GODER_TYPE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string MODIFIER_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime? MODIFY_DT { get; set; }
    
        /// <summary>
        /// 顾客类型 : 1直客 2同行
        /// </summary>
        public string USERTYPE { get; set; }
    }
}
