//-----------------------------------------------------------------------
// <copyright file=" jp_inner_mail_receiver.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_inner_mail_receiver.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jp_inner_mail_receiver Entity Model
    /// </summary>    
    [Table("jp_inner_mail_receiver")]
    public class jp_inner_mail_receiver : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _mail_id;
        /// <summary>
        /// 邮件标识
        /// </summary>
        public string mail_id
        {
            get { return _mail_id; }
            set { updateProper(ref _mail_id, value);}
        }
    
        private string _user_id;
        /// <summary>
        /// 收件人标识
        /// </summary>
        public string user_id
        {
            get { return _user_id; }
            set { updateProper(ref _user_id, value);}
        }
    
        private string _status;
        /// <summary>
        /// 收件状态
        /// </summary>
        public string status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _isdelete;
        /// <summary>
        /// 
        /// </summary>
        public string isdelete
        {
            get { return _isdelete; }
            set { updateProper(ref _isdelete, value);}
        }
    }
}
