//-----------------------------------------------------------------------
// <copyright file=" jp_inner_mail.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_inner_mail.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// jp_inner_mail Entity Model
    /// </summary>    
    [Table("jp_inner_mail")]
    public class jp_inner_mail : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _title;
        /// <summary>
        /// 主题
        /// </summary>
        public string title
        {
            get { return _title; }
            set { updateProper(ref _title, value);}
        }
    
        private string _attachment;
        /// <summary>
        /// 附件
        /// </summary>
        public string attachment
        {
            get { return _attachment; }
            set { updateProper(ref _attachment, value);}
        }
    
        private string _content;
        /// <summary>
        /// 内容
        /// </summary>
        public string content
        {
            get { return _content; }
            set { updateProper(ref _content, value);}
        }
    
        private string _status;
        /// <summary>
        /// 状态
        /// </summary>
        public string status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _receiver_names;
        /// <summary>
        /// 接收者姓名列表
        /// </summary>
        public string receiver_names
        {
            get { return _receiver_names; }
            set { updateProper(ref _receiver_names, value);}
        }
    
        private string _receiver_ids;
        /// <summary>
        /// 收件人标识列表
        /// </summary>
        public string receiver_ids
        {
            get { return _receiver_ids; }
            set { updateProper(ref _receiver_ids, value);}
        }
    }
}
