//-----------------------------------------------------------------------
// <copyright file=" jp_inner_mail.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_inner_mail.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// jp_inner_mail Entity Model
    /// </summary>    
export class jp_inner_mail
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 主题
        /// </summary>
    public title:string;
    
        /// <summary>
        /// 附件
        /// </summary>
    public attachment:string;
    
        /// <summary>
        /// 内容
        /// </summary>
    public content:string;
    
        /// <summary>
        /// 状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// 接收者姓名列表
        /// </summary>
    public receiver_names:string;
    
        /// <summary>
        /// 收件人标识列表
        /// </summary>
    public receiver_ids:string;
}

