//-----------------------------------------------------------------------
// <copyright file=" jp_inner_mail_attach.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: jp_inner_mail_attach.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// jp_inner_mail_attach Entity Model
    /// </summary>    
    [Serializable]
    public class jp_inner_mail_attach
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string mailid { get; set; }
    }
}
