//-----------------------------------------------------------------------
// <copyright file=" log_http_client.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: log_http_client.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// log_http_client Entity Model
    /// </summary>    
    [Table("log_http_client")]
    public class log_http_client : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _url;
        /// <summary>
        /// 请求地址
        /// </summary>
        public string url
        {
            get { return _url; }
            set { updateProper(ref _url, value);}
        }
    
        private DateTime? _date;
        /// <summary>
        /// 请求时间
        /// </summary>
        public DateTime? date
        {
            get { return _date; }
            set { updateProper(ref _date, value);}
        }
    
        private string _http_status;
        /// <summary>
        /// 请求状态
        /// </summary>
        public string http_status
        {
            get { return _http_status; }
            set { updateProper(ref _http_status, value);}
        }
    
        private string _data_status;
        /// <summary>
        /// 数据状态
        /// </summary>
        public string data_status
        {
            get { return _data_status; }
            set { updateProper(ref _data_status, value);}
        }
    
        private string _note;
        /// <summary>
        /// 备注
        /// </summary>
        public string note
        {
            get { return _note; }
            set { updateProper(ref _note, value);}
        }
    }
}
