//-----------------------------------------------------------------------
// <copyright file=" shipmodel.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: shipmodel.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// shipmodel Entity Model
    /// </summary>    
export class shipmodel
{
        /// <summary>
        /// 
        /// </summary>
    public Id:number;
    
        /// <summary>
        /// 
        /// </summary>
    public Name:string;
    
        /// <summary>
        /// 
        /// </summary>
    public Length:number;
    
        /// <summary>
        /// 
        /// </summary>
    public BuildTime:Date;
}

