//-----------------------------------------------------------------------
// <copyright file=" shipmodel.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: shipmodel.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// shipmodel Entity Model
    /// </summary>    
    [Table("shipmodel")]
    public class shipmodel : ObservableObject
    {
        private int? _Id;
        /// <summary>
        /// 
        /// </summary>        
        public int? Id
        {
            get { return _Id; }
            set { updateProper(ref _Id, value);}
        }
    
        private string _Name;
        /// <summary>
        /// 
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set { updateProper(ref _Name, value);}
        }
    
        private float? _Length;
        /// <summary>
        /// 
        /// </summary>
        public float? Length
        {
            get { return _Length; }
            set { updateProper(ref _Length, value);}
        }
    
        private DateTime? _BuildTime;
        /// <summary>
        /// 
        /// </summary>
        public DateTime? BuildTime
        {
            get { return _BuildTime; }
            set { updateProper(ref _BuildTime, value);}
        }
    }
}
