//-----------------------------------------------------------------------
// <copyright file=" t_s_typegroup.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_typegroup.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// t_s_typegroup Entity Model
    /// </summary>    
    [Table("t_s_typegroup")]
    public class t_s_typegroup
    {
        /// <summary>
        /// id
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 字典分组编码
        /// </summary>
        public string typegroupcode { get; set; }
    
        /// <summary>
        /// 字典分组名称
        /// </summary>
        public string typegroupname { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 创建用户
        /// </summary>
        public string create_name { get; set; }
    }
}
