//-----------------------------------------------------------------------
// <copyright file=" t_s_function.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_function.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_function Entity Model
    /// </summary>    
export class t_s_function
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 菜单地址打开方式
        /// </summary>
    public functioniframe:number;
    
        /// <summary>
        /// 菜单等级
        /// </summary>
    public functionlevel:number;
    
        /// <summary>
        /// 菜单名字
        /// </summary>
    public functionname:string;
    
        /// <summary>
        /// 排序
        /// </summary>
    public functionorder:string;
    
        /// <summary>
        /// URL
        /// </summary>
    public functionurl:string;
    
        /// <summary>
        /// 父菜单ID
        /// </summary>
    public parentfunctionid:string;
    
        /// <summary>
        /// 图标ID
        /// </summary>
    public iconid:string;
    
        /// <summary>
        /// 桌面图标ID
        /// </summary>
    public desk_iconid:string;
    
        /// <summary>
        /// 菜单类型
        /// </summary>
    public functiontype:number;
    
        /// <summary>
        /// ace图标样式
        /// </summary>
    public function_icon_style:string;
    
        /// <summary>
        /// 创建人id
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建人
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 修改人id
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 修改时间
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 创建时间
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 修改人
        /// </summary>
    public update_name:string;
}

