//-----------------------------------------------------------------------
// <copyright file=" t_s_function_group.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_function_group.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// t_s_function_group Entity Model
    /// </summary>    
    [Table("t_s_function_group")]
    public class t_s_function_group
    {
        /// <summary>
        /// ID
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 权限组名称
        /// </summary>
        public string group_name { get; set; }
    
        /// <summary>
        /// 部门ID
        /// </summary>
        public string dept_id { get; set; }
    
        /// <summary>
        /// 部门编码
        /// </summary>
        public string dept_code { get; set; }
    
        /// <summary>
        /// 部门名称
        /// </summary>
        public string dept_name { get; set; }
    
        /// <summary>
        /// 权限组父ID
        /// </summary>
        public string pid { get; set; }
    
        /// <summary>
        /// 级别
        /// </summary>
        public int? level { get; set; }
    
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人id
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 修改人id
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    }
}
