//-----------------------------------------------------------------------
// <copyright file=" t_s_operation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_operation.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_operation Entity Model
    /// </summary>    
    [Table("t_s_operation")]
    public class t_s_operation : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// id
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _operationcode;
        /// <summary>
        /// 页面控件code
        /// </summary>
        public string operationcode
        {
            get { return _operationcode; }
            set { updateProper(ref _operationcode, value);}
        }
    
        private string _operationicon;
        /// <summary>
        /// 图标
        /// </summary>
        public string operationicon
        {
            get { return _operationicon; }
            set { updateProper(ref _operationicon, value);}
        }
    
        private string _operationname;
        /// <summary>
        /// 页面名字
        /// </summary>
        public string operationname
        {
            get { return _operationname; }
            set { updateProper(ref _operationname, value);}
        }
    
        private int? _status;
        /// <summary>
        /// 状态
        /// </summary>
        public int? status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _functionid;
        /// <summary>
        /// 菜单ID
        /// </summary>
        public string functionid
        {
            get { return _functionid; }
            set { updateProper(ref _functionid, value);}
        }
    
        private string _iconid;
        /// <summary>
        /// 图标ID
        /// </summary>
        public string iconid
        {
            get { return _iconid; }
            set { updateProper(ref _iconid, value);}
        }
    
        private int? _operationtype;
        /// <summary>
        /// 规则类型：1/禁用 0/隐藏
        /// </summary>
        public int? operationtype
        {
            get { return _operationtype; }
            set { updateProper(ref _operationtype, value);}
        }
    }
}
