//-----------------------------------------------------------------------
// <copyright file=" t_s_region.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_region.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_region Entity Model
    /// </summary>    
export class t_s_region
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 城市名
        /// </summary>
    public NAME:string;
    
        /// <summary>
        /// 父ID
        /// </summary>
    public PID:string;
    
        /// <summary>
        /// 英文名
        /// </summary>
    public NAME_EN:string;
}

