//-----------------------------------------------------------------------
// <copyright file=" t_s_role_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_role_user.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_role_user Entity Model
    /// </summary>    
export class t_s_role_user
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 角色ID
        /// </summary>
    public roleid:string;
    
        /// <summary>
        /// 用户ID
        /// </summary>
    public userid:string;
}

