//-----------------------------------------------------------------------
// <copyright file=" t_s_document.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_document.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_document Entity Model
    /// </summary>    
    [Table("t_s_document")]
    public class t_s_document : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _typeid;
        /// <summary>
        /// 
        /// </summary>
        public string typeid
        {
            get { return _typeid; }
            set { updateProper(ref _typeid, value);}
        }
    
        private int? _documentstate;
        /// <summary>
        /// 
        /// </summary>
        public int? documentstate
        {
            get { return _documentstate; }
            set { updateProper(ref _documentstate, value);}
        }
    
        private string _documenttitle;
        /// <summary>
        /// 
        /// </summary>
        public string documenttitle
        {
            get { return _documenttitle; }
            set { updateProper(ref _documenttitle, value);}
        }
    
        private byte[] _pictureindex;
        /// <summary>
        /// 
        /// </summary>
        public byte[] pictureindex
        {
            get { return _pictureindex; }
            set { updateProper(ref _pictureindex, value);}
        }
    
        private int? _showhome;
        /// <summary>
        /// 
        /// </summary>
        public int? showhome
        {
            get { return _showhome; }
            set { updateProper(ref _showhome, value);}
        }
    }
}
