//-----------------------------------------------------------------------
// <copyright file=" t_s_function_group_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_function_group_user.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_function_group_user Entity Model
    /// </summary>    
export class t_s_function_group_user
{
        /// <summary>
        /// ID
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 权限组ID
        /// </summary>
    public group_id:string;
    
        /// <summary>
        /// 用户ID
        /// </summary>
    public user_id:string;
    
        /// <summary>
        /// 权限组类型
        /// </summary>
    public type:number;
    
        /// <summary>
        /// 创建人
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人id
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建时间
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 修改人
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 修改人id
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 修改时间
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
}

