//-----------------------------------------------------------------------
// <copyright file=" t_s_role_org.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_role_org.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// t_s_role_org Entity Model
    /// </summary>    
    [Serializable]
    public class t_s_role_org
    {
        /// <summary>
        /// id
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 机构ID
        /// </summary>
        public string org_id { get; set; }
    
        /// <summary>
        /// 角色ID
        /// </summary>
        public string role_id { get; set; }
    }
}
