//-----------------------------------------------------------------------
// <copyright file=" t_s_attachment.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_attachment.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_attachment Entity Model
    /// </summary>    
export class t_s_attachment
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 附件内容
        /// </summary>
    public attachmentcontent:longblob;
    
        /// <summary>
        /// 附件名称
        /// </summary>
    public attachmenttitle:string;
    
        /// <summary>
        /// 业务类主键
        /// </summary>
    public businesskey:string;
    
        /// <summary>
        /// 创建时间
        /// </summary>
    public createdate:Date;
    
        /// <summary>
        /// 扩展名
        /// </summary>
    public extend:string;
    
        /// <summary>
        /// note
        /// </summary>
    public note:string;
    
        /// <summary>
        /// 附件路径
        /// </summary>
    public realpath:string;
    
        /// <summary>
        /// 子类名称全路径
        /// </summary>
    public subclassname:string;
    
        /// <summary>
        /// swf格式路径
        /// </summary>
    public swfpath:string;
    
        /// <summary>
        /// BUSENTITYNAME
        /// </summary>
    public BUSENTITYNAME:string;
    
        /// <summary>
        /// INFOTYPEID
        /// </summary>
    public INFOTYPEID:string;
    
        /// <summary>
        /// 用户ID
        /// </summary>
    public USERID:string;
}

