//-----------------------------------------------------------------------
// <copyright file=" t_s_timetask.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_timetask.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// t_s_timetask Entity Model
    /// </summary>    
    [Serializable]
    public class t_s_timetask
    {
        /// <summary>
        /// id
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 创建人
        /// </summary>
        public string CREATE_BY { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CREATE_DATE { get; set; }
    
        /// <summary>
        /// 创建人名字
        /// </summary>
        public string CREATE_NAME { get; set; }
    
        /// <summary>
        /// cron表达式
        /// </summary>
        public string CRON_EXPRESSION { get; set; }
    
        /// <summary>
        /// 是否生效 0/未生效,1/生效
        /// </summary>
        public string IS_EFFECT { get; set; }
    
        /// <summary>
        /// 是否运行0停止,1运行
        /// </summary>
        public string IS_START { get; set; }
    
        /// <summary>
        /// 任务描述
        /// </summary>
        public string TASK_DESCRIBE { get; set; }
    
        /// <summary>
        /// 任务ID
        /// </summary>
        public string TASK_ID { get; set; }
    
        /// <summary>
        /// 任务类名
        /// </summary>
        public string CLASS_NAME { get; set; }
    
        /// <summary>
        /// 任务运行服务器IP
        /// </summary>
        public string RUN_SERVER_IP { get; set; }
    
        /// <summary>
        /// 远程主机（域名/IP+项目路径）
        /// </summary>
        public string RUN_SERVER { get; set; }
    
        /// <summary>
        /// 修改人
        /// </summary>
        public string UPDATE_BY { get; set; }
    
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime UPDATE_DATE { get; set; }
    
        /// <summary>
        /// 修改人名称
        /// </summary>
        public string UPDATE_NAME { get; set; }
    }
}
