//-----------------------------------------------------------------------
// <copyright file=" t_s_document.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_document.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// t_s_document Entity Model
    /// </summary>    
    [Table("t_s_document")]
    public class t_s_document
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string typeid { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int? documentstate { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string documenttitle { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public byte[] pictureindex { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int? showhome { get; set; }
    }
}
