//-----------------------------------------------------------------------
// <copyright file=" t_s_typegroup.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_typegroup.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_typegroup Entity Model
    /// </summary>    
export class t_s_typegroup
{
        /// <summary>
        /// id
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 字典分组编码
        /// </summary>
    public typegroupcode:string;
    
        /// <summary>
        /// 字典分组名称
        /// </summary>
    public typegroupname:string;
    
        /// <summary>
        /// 创建时间
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 创建用户
        /// </summary>
    public create_name:string;
}

