//-----------------------------------------------------------------------
// <copyright file=" t_s_type.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_type.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// t_s_type Entity Model
    /// </summary>    
    [Serializable]
    public class t_s_type
    {
        /// <summary>
        /// id
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 字典编码
        /// </summary>
        public string typecode { get; set; }
    
        /// <summary>
        /// 字典名称
        /// </summary>
        public string typename { get; set; }
    
        /// <summary>
        /// 无用字段
        /// </summary>
        public string typepid { get; set; }
    
        /// <summary>
        /// 字典组ID
        /// </summary>
        public string typegroupid { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime create_date { get; set; }
    
        /// <summary>
        /// 创建用户
        /// </summary>
        public string create_name { get; set; }
    }
}
