//-----------------------------------------------------------------------
// <copyright file=" t_s_type.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_type.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_type Entity Model
    /// </summary>    
    [Table("t_s_type")]
    public class t_s_type : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// id
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _typecode;
        /// <summary>
        /// 字典编码
        /// </summary>
        public string typecode
        {
            get { return _typecode; }
            set { updateProper(ref _typecode, value);}
        }
    
        private string _typename;
        /// <summary>
        /// 字典名称
        /// </summary>
        public string typename
        {
            get { return _typename; }
            set { updateProper(ref _typename, value);}
        }
    
        private string _typepid;
        /// <summary>
        /// 无用字段
        /// </summary>
        public string typepid
        {
            get { return _typepid; }
            set { updateProper(ref _typepid, value);}
        }
    
        private string _typegroupid;
        /// <summary>
        /// 字典组ID
        /// </summary>
        public string typegroupid
        {
            get { return _typegroupid; }
            set { updateProper(ref _typegroupid, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建用户
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    }
}
