//-----------------------------------------------------------------------
// <copyright file=" t_s_role_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_role_user.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// t_s_role_user Entity Model
    /// </summary>    
    [Serializable]
    public class t_s_role_user
    {
        /// <summary>
        /// ID
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 角色ID
        /// </summary>
        public string roleid { get; set; }
    
        /// <summary>
        /// 用户ID
        /// </summary>
        public string userid { get; set; }
    }
}
