//-----------------------------------------------------------------------
// <copyright file=" t_s_log.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_log.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_log Entity Model
    /// </summary>    
export class t_s_log
{
        /// <summary>
        /// id
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 浏览器
        /// </summary>
    public broswer:string;
    
        /// <summary>
        /// 日志内容
        /// </summary>
    public logcontent:string;
    
        /// <summary>
        /// 日志级别
        /// </summary>
    public loglevel:number;
    
        /// <summary>
        /// IP
        /// </summary>
    public note:string;
    
        /// <summary>
        /// 操作时间
        /// </summary>
    public operatetime:Date;
    
        /// <summary>
        /// 操作类型
        /// </summary>
    public operatetype:number;
    
        /// <summary>
        /// 用户ID
        /// </summary>
    public userid:string;
    
        /// <summary>
        /// 用户账号
        /// </summary>
    public username:string;
    
        /// <summary>
        /// 真实名字
        /// </summary>
    public realname:string;
}

