//-----------------------------------------------------------------------
// <copyright file=" t_s_depart.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_depart.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_depart Entity Model
    /// </summary>    
export class t_s_depart
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 部门名称
        /// </summary>
    public departname:string;
    
        /// <summary>
        /// 描述
        /// </summary>
    public description:string;
    
        /// <summary>
        /// 父部门ID
        /// </summary>
    public parentdepartid:string;
    
        /// <summary>
        /// 机构编码
        /// </summary>
    public org_code:string;
    
        /// <summary>
        /// 机构类型
        /// </summary>
    public org_type:string;
    
        /// <summary>
        /// 手机号
        /// </summary>
    public mobile:string;
    
        /// <summary>
        /// 传真
        /// </summary>
    public fax:string;
    
        /// <summary>
        /// 地址
        /// </summary>
    public address:string;
    
        /// <summary>
        /// 排序
        /// </summary>
    public depart_order:string;
}

