//-----------------------------------------------------------------------
// <copyright file=" t_s_role.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_role.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_role Entity Model
    /// </summary>    
export class t_s_role
{
        /// <summary>
        /// ID
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 角色编码
        /// </summary>
    public rolecode:string;
    
        /// <summary>
        /// 角色名字
        /// </summary>
    public rolename:string;
    
        /// <summary>
        /// 修改人
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 修改时间
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 修改人id
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 创建人
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建时间
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 创建人id
        /// </summary>
    public create_by:string;
}

