//-----------------------------------------------------------------------
// <copyright file=" t_s_region.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_region.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// t_s_region Entity Model
    /// </summary>    
    [Table("t_s_region")]
    public class t_s_region
    {
        /// <summary>
        /// ID
        /// </summary>
        public string ID { get; set; }
    
        /// <summary>
        /// 城市名
        /// </summary>
        public string NAME { get; set; }
    
        /// <summary>
        /// 父ID
        /// </summary>
        public string PID { get; set; }
    
        /// <summary>
        /// 英文名
        /// </summary>
        public string NAME_EN { get; set; }
    }
}
