//-----------------------------------------------------------------------
// <copyright file=" t_s_base_user.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_base_user.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_base_user Entity Model
    /// </summary>    
    [Table("t_s_base_user")]
    public class t_s_base_user : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private int? _activitiSync;
        /// <summary>
        /// 同步流程
        /// </summary>
        public int? activitiSync
        {
            get { return _activitiSync; }
            set { updateProper(ref _activitiSync, value);}
        }
    
        private string _browser;
        /// <summary>
        /// 浏览器
        /// </summary>
        public string browser
        {
            get { return _browser; }
            set { updateProper(ref _browser, value);}
        }
    
        private string _password;
        /// <summary>
        /// 密码
        /// </summary>
        public string password
        {
            get { return _password; }
            set { updateProper(ref _password, value);}
        }
    
        private string _realname;
        /// <summary>
        /// 真实名字
        /// </summary>
        public string realname
        {
            get { return _realname; }
            set { updateProper(ref _realname, value);}
        }
    
        private byte[] _signature;
        /// <summary>
        /// 签名
        /// </summary>
        public byte[] signature
        {
            get { return _signature; }
            set { updateProper(ref _signature, value);}
        }
    
        private int? _status;
        /// <summary>
        /// 有效状态
        /// </summary>
        public int? status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _userkey;
        /// <summary>
        /// 用户KEY
        /// </summary>
        public string userkey
        {
            get { return _userkey; }
            set { updateProper(ref _userkey, value);}
        }
    
        private string _username;
        /// <summary>
        /// 用户账号
        /// </summary>
        public string username
        {
            get { return _username; }
            set { updateProper(ref _username, value);}
        }
    
        private string _departid;
        /// <summary>
        /// 部门ID
        /// </summary>
        public string departid
        {
            get { return _departid; }
            set { updateProper(ref _departid, value);}
        }
    
        private int? _delete_flag;
        /// <summary>
        /// 删除状态
        /// </summary>
        public int? delete_flag
        {
            get { return _delete_flag; }
            set { updateProper(ref _delete_flag, value);}
        }
    }
}
