//-----------------------------------------------------------------------
// <copyright file=" t_s_role_org.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_role_org.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_role_org Entity Model
    /// </summary>    
    [Table("t_s_role_org")]
    public class t_s_role_org : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// id
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private string _org_id;
        /// <summary>
        /// 机构ID
        /// </summary>
        public string org_id
        {
            get { return _org_id; }
            set { updateProper(ref _org_id, value);}
        }
    
        private string _role_id;
        /// <summary>
        /// 角色ID
        /// </summary>
        public string role_id
        {
            get { return _role_id; }
            set { updateProper(ref _role_id, value);}
        }
    }
}
