//-----------------------------------------------------------------------
// <copyright file=" t_s_function.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_function.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// t_s_function Entity Model
    /// </summary>    
    [Table("t_s_function")]
    public class t_s_function : ObservableObject
    {
        private string _ID;
        /// <summary>
        /// ID
        /// </summary>        
        public string ID
        {
            get { return _ID; }
            set { updateProper(ref _ID, value);}
        }
    
        private int? _functioniframe;
        /// <summary>
        /// 菜单地址打开方式
        /// </summary>
        public int? functioniframe
        {
            get { return _functioniframe; }
            set { updateProper(ref _functioniframe, value);}
        }
    
        private int? _functionlevel;
        /// <summary>
        /// 菜单等级
        /// </summary>
        public int? functionlevel
        {
            get { return _functionlevel; }
            set { updateProper(ref _functionlevel, value);}
        }
    
        private string _functionname;
        /// <summary>
        /// 菜单名字
        /// </summary>
        public string functionname
        {
            get { return _functionname; }
            set { updateProper(ref _functionname, value);}
        }
    
        private string _functionorder;
        /// <summary>
        /// 排序
        /// </summary>
        public string functionorder
        {
            get { return _functionorder; }
            set { updateProper(ref _functionorder, value);}
        }
    
        private string _functionurl;
        /// <summary>
        /// URL
        /// </summary>
        public string functionurl
        {
            get { return _functionurl; }
            set { updateProper(ref _functionurl, value);}
        }
    
        private string _parentfunctionid;
        /// <summary>
        /// 父菜单ID
        /// </summary>
        public string parentfunctionid
        {
            get { return _parentfunctionid; }
            set { updateProper(ref _parentfunctionid, value);}
        }
    
        private string _iconid;
        /// <summary>
        /// 图标ID
        /// </summary>
        public string iconid
        {
            get { return _iconid; }
            set { updateProper(ref _iconid, value);}
        }
    
        private string _desk_iconid;
        /// <summary>
        /// 桌面图标ID
        /// </summary>
        public string desk_iconid
        {
            get { return _desk_iconid; }
            set { updateProper(ref _desk_iconid, value);}
        }
    
        private int? _functiontype;
        /// <summary>
        /// 菜单类型
        /// </summary>
        public int? functiontype
        {
            get { return _functiontype; }
            set { updateProper(ref _functiontype, value);}
        }
    
        private string _function_icon_style;
        /// <summary>
        /// ace图标样式
        /// </summary>
        public string function_icon_style
        {
            get { return _function_icon_style; }
            set { updateProper(ref _function_icon_style, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人id
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 修改人id
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 修改人
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    }
}
