//-----------------------------------------------------------------------
// <copyright file=" t_s_operation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_s_operation.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// t_s_operation Entity Model
    /// </summary>    
export class t_s_operation
{
        /// <summary>
        /// id
        /// </summary>
    public ID:string;
    
        /// <summary>
        /// 页面控件code
        /// </summary>
    public operationcode:string;
    
        /// <summary>
        /// 图标
        /// </summary>
    public operationicon:string;
    
        /// <summary>
        /// 页面名字
        /// </summary>
    public operationname:string;
    
        /// <summary>
        /// 状态
        /// </summary>
    public status:number;
    
        /// <summary>
        /// 菜单ID
        /// </summary>
    public functionid:string;
    
        /// <summary>
        /// 图标ID
        /// </summary>
    public iconid:string;
    
        /// <summary>
        /// 规则类型：1/禁用 0/隐藏
        /// </summary>
    public operationtype:number;
}

