//-----------------------------------------------------------------------
// <copyright file=" task_form.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: task_form.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// task_form Entity Model
    /// </summary>    
    [Table("task_form")]
    public class task_form
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 表单dataId
        /// </summary>
        public string data_id { get; set; }
    
        /// <summary>
        /// 表单id
        /// </summary>
        public string form_id { get; set; }
    
        /// <summary>
        /// objectCode
        /// </summary>
        public string object_code { get; set; }
    
        /// <summary>
        /// objectType
        /// </summary>
        public string object_type { get; set; }
    
        /// <summary>
        /// object_code
        /// </summary>
        public string business_object_code { get; set; }
    
        /// <summary>
        /// subject
        /// </summary>
        public string subject { get; set; }
    
        /// <summary>
        /// 用户Code
        /// </summary>
        public string user_code { get; set; }
    
        /// <summary>
        /// apply_ucid
        /// </summary>
        public string apply_ucid { get; set; }
    
        /// <summary>
        /// 申请编号
        /// </summary>
        public string receive_number { get; set; }
    
        /// <summary>
        /// 用户名
        /// </summary>
        public string user_name { get; set; }
    
        /// <summary>
        /// 办结时间
        /// </summary>
        public DateTime? over_time { get; set; }
    
        /// <summary>
        /// 申请人
        /// </summary>
        public string apply_account { get; set; }
    
        /// <summary>
        /// object_type
        /// </summary>
        public string business_object_type { get; set; }
    
        /// <summary>
        /// 事项名称
        /// </summary>
        public string item_name { get; set; }
    
        /// <summary>
        /// 事项ID
        /// </summary>
        public string item_id { get; set; }
    
        /// <summary>
        /// apply_from
        /// </summary>
        public string apply_from { get; set; }
    
        /// <summary>
        /// opinion
        /// </summary>
        public string opinion { get; set; }
    
        /// <summary>
        /// 受理时间
        /// </summary>
        public DateTime? submit_time { get; set; }
    
        /// <summary>
        /// 状态
        /// </summary>
        public string status { get; set; }
    
        /// <summary>
        /// 事项类型
        /// </summary>
        public string type { get; set; }
    
        /// <summary>
        /// 证照编号
        /// </summary>
        public string license_number { get; set; }
    
        /// <summary>
        /// 详情信息
        /// </summary>
        public string json_str { get; set; }
    
        /// <summary>
        /// 证照信息
        /// </summary>
        public string license_str { get; set; }
    
        /// <summary>
        /// 更改前详细信息
        /// </summary>
        public string json_old_str { get; set; }
    
        /// <summary>
        /// 更改前证照信息
        /// </summary>
        public string license_old_str { get; set; }
    
        /// <summary>
        /// 更新主表id
        /// </summary>
        public string primary_id { get; set; }
    }
}
