//-----------------------------------------------------------------------
// <copyright file=" test_person.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: test_person.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// test_person Entity Model
    /// </summary>    
    [Table("test_person")]
    public class test_person
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 名字
        /// </summary>
        public string name { get; set; }
    
        /// <summary>
        /// 性别
        /// </summary>
        public string sex { get; set; }
    
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? birthday { get; set; }
    
        /// <summary>
        /// 个人简介
        /// </summary>
        public string conets { get; set; }
    
        /// <summary>
        /// 测性别
        /// </summary>
        public string cexs { get; set; }
    
        /// <summary>
        /// 工资
        /// </summary>
        public double? salary { get; set; }
    
        /// <summary>
        /// 简历附件
        /// </summary>
        public string fiel_jls { get; set; }
    
        /// <summary>
        /// 个人头像
        /// </summary>
        public string tou_pic { get; set; }
    }
}
