//-----------------------------------------------------------------------
// <copyright file=" tmp_tables.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: tmp_tables.cs
// * history : Created by T4 03/22/2018 16:26:40 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace Console4Test
{
    /// <summary>
    /// tmp_tables Entity Model
    /// </summary>    
    [Serializable]
    public class tmp_tables
    {
        /// <summary>
        /// 
        /// </summary>
        public int id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string wl_table_name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string xt_table_name { get; set; }
    }
}
