//-----------------------------------------------------------------------
// <copyright file=" yz_enterprises_inverstor.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_enterprises_inverstor.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_enterprises_inverstor Entity Model
    /// </summary>    
export class yz_enterprises_inverstor
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 个人或企业
        /// </summary>
    public investor_type:string;
    
        /// <summary>
        /// 投资人名称
        /// </summary>
    public investor_name:string;
    
        /// <summary>
        /// 资金
        /// </summary>
    public money:string;
    
        /// <summary>
        /// 投资比例
        /// </summary>
    public ratio:string;
    
        /// <summary>
        /// 证件号
        /// </summary>
    public cadr_no:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public reamark:string;
    
        /// <summary>
        /// 关联ID
        /// </summary>
    public operator_id:string;
}

