//-----------------------------------------------------------------------
// <copyright file=" yz_enterprise_yearcheck.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_enterprise_yearcheck.cs
// * history : Created by T4 03/28/2018 17:16:33 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// yz_enterprise_yearcheck Entity Model
    /// </summary>    
    [Table("yz_enterprise_yearcheck")]
    public class yz_enterprise_yearcheck : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _chinese_name;
        /// <summary>
        /// 企业中文名称
        /// </summary>
        public string chinese_name
        {
            get { return _chinese_name; }
            set { updateProper(ref _chinese_name, value);}
        }
    
        private string _legal_person;
        /// <summary>
        /// 法定代表人
        /// </summary>
        public string legal_person
        {
            get { return _legal_person; }
            set { updateProper(ref _legal_person, value);}
        }
    
        private string _economic_type;
        /// <summary>
        /// 经济类型
        /// </summary>
        public string economic_type
        {
            get { return _economic_type; }
            set { updateProper(ref _economic_type, value);}
        }
    
        private string _register_money;
        /// <summary>
        /// 注册资本
        /// </summary>
        public string register_money
        {
            get { return _register_money; }
            set { updateProper(ref _register_money, value);}
        }
    
        private string _register_address;
        /// <summary>
        /// 注册地址
        /// </summary>
        public string register_address
        {
            get { return _register_address; }
            set { updateProper(ref _register_address, value);}
        }
    
        private string _phone;
        /// <summary>
        /// 联系电话
        /// </summary>
        public string phone
        {
            get { return _phone; }
            set { updateProper(ref _phone, value);}
        }
    
        private string _operator_address;
        /// <summary>
        /// 经营地址
        /// </summary>
        public string operator_address
        {
            get { return _operator_address; }
            set { updateProper(ref _operator_address, value);}
        }
    
        private string _fax;
        /// <summary>
        /// 传真
        /// </summary>
        public string fax
        {
            get { return _fax; }
            set { updateProper(ref _fax, value);}
        }
    
        private string _certificate_organ;
        /// <summary>
        /// 许可证发证机关
        /// </summary>
        public string certificate_organ
        {
            get { return _certificate_organ; }
            set { updateProper(ref _certificate_organ, value);}
        }
    
        private string _certificate_number;
        /// <summary>
        /// 许可证编号
        /// </summary>
        public string certificate_number
        {
            get { return _certificate_number; }
            set { updateProper(ref _certificate_number, value);}
        }
    
        private string _business_area;
        /// <summary>
        /// 经营范围
        /// </summary>
        public string business_area
        {
            get { return _business_area; }
            set { updateProper(ref _business_area, value);}
        }
    
        private string _check_year;
        /// <summary>
        /// 年审年份
        /// </summary>
        public string check_year
        {
            get { return _check_year; }
            set { updateProper(ref _check_year, value);}
        }
    
        private DateTime? _apply_date;
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime? apply_date
        {
            get { return _apply_date; }
            set { updateProper(ref _apply_date, value);}
        }
    
        private string _terminal_total;
        /// <summary>
        /// 期末总资产
        /// </summary>
        public string terminal_total
        {
            get { return _terminal_total; }
            set { updateProper(ref _terminal_total, value);}
        }
    
        private string _terminal_clean;
        /// <summary>
        /// 期末净资产
        /// </summary>
        public string terminal_clean
        {
            get { return _terminal_clean; }
            set { updateProper(ref _terminal_clean, value);}
        }
    
        private string _tran_income;
        /// <summary>
        /// 运输或营业收入
        /// </summary>
        public string tran_income
        {
            get { return _tran_income; }
            set { updateProper(ref _tran_income, value);}
        }
    
        private string _tran_cost;
        /// <summary>
        /// 运输或营业成本
        /// </summary>
        public string tran_cost
        {
            get { return _tran_cost; }
            set { updateProper(ref _tran_cost, value);}
        }
    
        private string _diesel_use;
        /// <summary>
        /// 船用柴油消耗量
        /// </summary>
        public string diesel_use
        {
            get { return _diesel_use; }
            set { updateProper(ref _diesel_use, value);}
        }
    
        private string _fuel_use;
        /// <summary>
        /// 船用燃料油消耗量
        /// </summary>
        public string fuel_use
        {
            get { return _fuel_use; }
            set { updateProper(ref _fuel_use, value);}
        }
    
        private string _freight_number;
        /// <summary>
        /// 货运量
        /// </summary>
        public string freight_number
        {
            get { return _freight_number; }
            set { updateProper(ref _freight_number, value);}
        }
    
        private string _passenger_number;
        /// <summary>
        /// 客运量
        /// </summary>
        public string passenger_number
        {
            get { return _passenger_number; }
            set { updateProper(ref _passenger_number, value);}
        }
    
        private string _freight_turnover;
        /// <summary>
        /// 货运周转量
        /// </summary>
        public string freight_turnover
        {
            get { return _freight_turnover; }
            set { updateProper(ref _freight_turnover, value);}
        }
    
        private string _passenger_turnover;
        /// <summary>
        /// 客运周转量
        /// </summary>
        public string passenger_turnover
        {
            get { return _passenger_turnover; }
            set { updateProper(ref _passenger_turnover, value);}
        }
    
        private string _passenger_proxy;
        /// <summary>
        /// 客运代理量
        /// </summary>
        public string passenger_proxy
        {
            get { return _passenger_proxy; }
            set { updateProper(ref _passenger_proxy, value);}
        }
    
        private string _ship_proxy;
        /// <summary>
        /// 船舶代理量
        /// </summary>
        public string ship_proxy
        {
            get { return _ship_proxy; }
            set { updateProper(ref _ship_proxy, value);}
        }
    
        private string _goods_proxy;
        /// <summary>
        /// 货物代理量
        /// </summary>
        public string goods_proxy
        {
            get { return _goods_proxy; }
            set { updateProper(ref _goods_proxy, value);}
        }
    
        private string _ship_manage;
        /// <summary>
        /// 船舶管理量
        /// </summary>
        public string ship_manage
        {
            get { return _ship_manage; }
            set { updateProper(ref _ship_manage, value);}
        }
    
        private string _safe_system;
        /// <summary>
        /// 安全管理体系情况
        /// </summary>
        public string safe_system
        {
            get { return _safe_system; }
            set { updateProper(ref _safe_system, value);}
        }
    
        private string _doc_number;
        /// <summary>
        /// 符合证明DOC编号
        /// </summary>
        public string doc_number
        {
            get { return _doc_number; }
            set { updateProper(ref _doc_number, value);}
        }
    
        private string _produce_analysis;
        /// <summary>
        /// 上年度生产经营情况分析
        /// </summary>
        public string produce_analysis
        {
            get { return _produce_analysis; }
            set { updateProper(ref _produce_analysis, value);}
        }
    
        private string _measure_analysis;
        /// <summary>
        /// 上年度安全生产情况及措施
        /// </summary>
        public string measure_analysis
        {
            get { return _measure_analysis; }
            set { updateProper(ref _measure_analysis, value);}
        }
    
        private string _question_exist;
        /// <summary>
        /// 存在的困难和问题
        /// </summary>
        public string question_exist
        {
            get { return _question_exist; }
            set { updateProper(ref _question_exist, value);}
        }
    
        private string _suggestion;
        /// <summary>
        /// 建议和意见
        /// </summary>
        public string suggestion
        {
            get { return _suggestion; }
            set { updateProper(ref _suggestion, value);}
        }
    
        private string _remark;
        /// <summary>
        /// 备注
        /// </summary>
        public string remark
        {
            get { return _remark; }
            set { updateProper(ref _remark, value);}
        }
    
        private string _status;
        /// <summary>
        /// 状态
        /// </summary>
        public string status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _enterprise_id;
        /// <summary>
        /// 
        /// </summary>
        public string enterprise_id
        {
            get { return _enterprise_id; }
            set { updateProper(ref _enterprise_id, value);}
        }
    }
}
