//-----------------------------------------------------------------------
// <copyright file=" yz_enterprises_inverstor.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_enterprises_inverstor.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// yz_enterprises_inverstor Entity Model
    /// </summary>    
    [Table("yz_enterprises_inverstor")]
    public class yz_enterprises_inverstor
    {
        /// <summary>
        /// 主键
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 个人或企业
        /// </summary>
        public string investor_type { get; set; }
    
        /// <summary>
        /// 投资人名称
        /// </summary>
        public string investor_name { get; set; }
    
        /// <summary>
        /// 资金
        /// </summary>
        public string money { get; set; }
    
        /// <summary>
        /// 投资比例
        /// </summary>
        public string ratio { get; set; }
    
        /// <summary>
        /// 证件号
        /// </summary>
        public string cadr_no { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>
        public string reamark { get; set; }
    
        /// <summary>
        /// 关联ID
        /// </summary>
        public string operator_id { get; set; }
    }
}
