//-----------------------------------------------------------------------
// <copyright file=" yz_enterprises_manager.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_enterprises_manager.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_enterprises_manager Entity Model
    /// </summary>    
export class yz_enterprises_manager
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 姓名
        /// </summary>
    public name:string;
    
        /// <summary>
        /// 性别
        /// </summary>
    public sex:string;
    
        /// <summary>
        /// 身份证号
        /// </summary>
    public card_no:string;
    
        /// <summary>
        /// 所在部门
        /// </summary>
    public dept:string;
    
        /// <summary>
        /// 职务
        /// </summary>
    public duty:string;
    
        /// <summary>
        /// 适任证书类型
        /// </summary>
    public duty_certificate_type:string;
    
        /// <summary>
        /// 适任证书编号
        /// </summary>
    public duty_certificate_no:string;
    
        /// <summary>
        /// 聘用合同起
        /// </summary>
    public contract_start_date:Date;
    
        /// <summary>
        /// 聘用合同至
        /// </summary>
    public contract_end_date:Date;
    
        /// <summary>
        /// 联系地址
        /// </summary>
    public address:string;
    
        /// <summary>
        /// 联系电话
        /// </summary>
    public phone:string;
    
        /// <summary>
        /// 电子邮件
        /// </summary>
    public email:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public remark:string;
    
        /// <summary>
        /// 关联ID
        /// </summary>
    public operator_id:string;
}

