//-----------------------------------------------------------------------
// <copyright file=" yz_operator_scale.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_scale.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_operator_scale Entity Model
    /// </summary>    
export class yz_operator_scale
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 船舶类型
        /// </summary>
    public ship_type:string;
    
        /// <summary>
        /// 船舶来历
        /// </summary>
    public ship_source:string;
    
        /// <summary>
        /// 船舶艘数
        /// </summary>
    public ship_num:string;
    
        /// <summary>
        /// 船舶总吨
        /// </summary>
    public total_ton:string;
    
        /// <summary>
        /// 载重吨
        /// </summary>
    public load_ton:string;
    
        /// <summary>
        /// 船舶净吨
        /// </summary>
    public suttle_ton:string;
    
        /// <summary>
        /// 载客量
        /// </summary>
    public passenger_capacity:string;
    
        /// <summary>
        /// 载箱量
        /// </summary>
    public containe_capacity:string;
    
        /// <summary>
        /// 载车量
        /// </summary>
    public vehicle_capacity:string;
    
        /// <summary>
        /// 载气量
        /// </summary>
    public gas_capacity:string;
    
        /// <summary>
        /// 主机总台数
        /// </summary>
    public mainframe_total_num:string;
    
        /// <summary>
        /// 主机总功率
        /// </summary>
    public mainframe_total_power:string;
    
        /// <summary>
        /// 关联id
        /// </summary>
    public operator_id:string;
}

