//-----------------------------------------------------------------------
// <copyright file=" yz_operator_yearcheck.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_yearcheck.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_operator_yearcheck Entity Model
    /// </summary>    
export class yz_operator_yearcheck
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 经营者中文名称
        /// </summary>
    public chinese_name:string;
    
        /// <summary>
        /// 法定代表人
        /// </summary>
    public legal_person:string;
    
        /// <summary>
        /// 经济类型
        /// </summary>
    public economic_type:string;
    
        /// <summary>
        /// 注册资本
        /// </summary>
    public register_money:string;
    
        /// <summary>
        /// 注册地址
        /// </summary>
    public register_address:string;
    
        /// <summary>
        /// 联系电话
        /// </summary>
    public phone:string;
    
        /// <summary>
        /// 经营地址
        /// </summary>
    public operator_address:string;
    
        /// <summary>
        /// 传真
        /// </summary>
    public fax:string;
    
        /// <summary>
        /// 许可证发证机关
        /// </summary>
    public certificate_organ:string;
    
        /// <summary>
        /// 许可证编号
        /// </summary>
    public certificate_number:string;
    
        /// <summary>
        /// 许可证核定的客运经营范围
        /// </summary>
    public passenger_area:string;
    
        /// <summary>
        /// 许可证核定的货运经营范围
        /// </summary>
    public freight_area:string;
    
        /// <summary>
        /// 年审年份
        /// </summary>
    public check_year:string;
    
        /// <summary>
        /// 申请日期
        /// </summary>
    public apply_date:Date;
    
        /// <summary>
        /// 期末总资产
        /// </summary>
    public terminal_total:string;
    
        /// <summary>
        /// 期末净资产
        /// </summary>
    public terminal_clean:string;
    
        /// <summary>
        /// 运输或营业收入
        /// </summary>
    public tran_income:string;
    
        /// <summary>
        /// 运输或营业成本
        /// </summary>
    public tran_cost:string;
    
        /// <summary>
        /// 船用柴油消耗量
        /// </summary>
    public diesel_use:string;
    
        /// <summary>
        /// 船用燃料油消耗量
        /// </summary>
    public fuel_use:string;
    
        /// <summary>
        /// 货运量
        /// </summary>
    public freight_number:string;
    
        /// <summary>
        /// 客运量
        /// </summary>
    public passenger_number:string;
    
        /// <summary>
        /// 货运周转量
        /// </summary>
    public freight_turnover:string;
    
        /// <summary>
        /// 客运周转量
        /// </summary>
    public passenger_turnover:string;
    
        /// <summary>
        /// 客运代理量
        /// </summary>
    public passenger_proxy:string;
    
        /// <summary>
        /// 船舶代理量
        /// </summary>
    public ship_proxy:string;
    
        /// <summary>
        /// 货物代理量
        /// </summary>
    public goods_proxy:string;
    
        /// <summary>
        /// 船舶管理量
        /// </summary>
    public ship_manage:string;
    
        /// <summary>
        /// 安全管理体系情况
        /// </summary>
    public safe_system:string;
    
        /// <summary>
        /// 符合证明DOC编号
        /// </summary>
    public doc_number:string;
    
        /// <summary>
        /// 上年度生产经营情况分析
        /// </summary>
    public produce_analysis:string;
    
        /// <summary>
        /// 上年度安全生产情况及措施
        /// </summary>
    public measure_analysis:string;
    
        /// <summary>
        /// 存在的困难和问题
        /// </summary>
    public question_exist:string;
    
        /// <summary>
        /// 建议和意见
        /// </summary>
    public suggestion:string;
    
        /// <summary>
        /// 备注
        /// </summary>
    public remark:string;
    
        /// <summary>
        /// 状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// 
        /// </summary>
    public operator_id:string;
}

