//-----------------------------------------------------------------------
// <copyright file=" yz_operator_certificate.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_certificate.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_operator_certificate Entity Model
    /// </summary>    
export class yz_operator_certificate
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 许可证编号
        /// </summary>
    public certificate_code:string;
    
        /// <summary>
        /// 经营期限
        /// </summary>
    public period:string;
    
        /// <summary>
        /// 批准机关及文号
        /// </summary>
    public certificate_dept:string;
    
        /// <summary>
        /// 发证日期
        /// </summary>
    public release_date:Date;
    
        /// <summary>
        /// 有效期至
        /// </summary>
    public expiry_date:Date;
    
        /// <summary>
        /// 证书状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// 关联id
        /// </summary>
    public operator_id:string;
}

