//-----------------------------------------------------------------------
// <copyright file=" yz_operator_transportation.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_transportation.cs
// * history : Created by T4 03/23/2018 15:18:04 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// yz_operator_transportation Entity Model
    /// </summary>    
    [Table("yz_operator_transportation")]
    public class yz_operator_transportation
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 经营范围
        /// </summary>
        public string business_scope { get; set; }
    
        /// <summary>
        /// 经营区域
        /// </summary>
        public string business_asea { get; set; }
    
        /// <summary>
        /// 水系
        /// </summary>
        public string river_system { get; set; }
    
        /// <summary>
        /// 运输船舶种类
        /// </summary>
        public string ship_type { get; set; }
    
        /// <summary>
        /// 关联ID
        /// </summary>
        public string operator_id { get; set; }
    }
}
