//-----------------------------------------------------------------------
// <copyright file=" yz_operator_scale.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_scale.cs
// * history : Created by T4 03/23/2018 16:39:14 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChongQingNetCheckWebService.Models
{
    /// <summary>
    /// yz_operator_scale Entity Model
    /// </summary>    
    [Table("yz_operator_scale")]
    public class yz_operator_scale
    {
        /// <summary>
        /// 
        /// </summary>
        public string id { get; set; }
    
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name { get; set; }
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date { get; set; }
    
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name { get; set; }
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by { get; set; }
    
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date { get; set; }
    
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code { get; set; }
    
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code { get; set; }
    
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status { get; set; }
    
        /// <summary>
        /// 船舶类型
        /// </summary>
        public string ship_type { get; set; }
    
        /// <summary>
        /// 船舶来历
        /// </summary>
        public string ship_source { get; set; }
    
        /// <summary>
        /// 船舶艘数
        /// </summary>
        public string ship_num { get; set; }
    
        /// <summary>
        /// 船舶总吨
        /// </summary>
        public string total_ton { get; set; }
    
        /// <summary>
        /// 载重吨
        /// </summary>
        public string load_ton { get; set; }
    
        /// <summary>
        /// 船舶净吨
        /// </summary>
        public string suttle_ton { get; set; }
    
        /// <summary>
        /// 载客量
        /// </summary>
        public string passenger_capacity { get; set; }
    
        /// <summary>
        /// 载箱量
        /// </summary>
        public string containe_capacity { get; set; }
    
        /// <summary>
        /// 载车量
        /// </summary>
        public string vehicle_capacity { get; set; }
    
        /// <summary>
        /// 载气量
        /// </summary>
        public string gas_capacity { get; set; }
    
        /// <summary>
        /// 主机总台数
        /// </summary>
        public string mainframe_total_num { get; set; }
    
        /// <summary>
        /// 主机总功率
        /// </summary>
        public string mainframe_total_power { get; set; }
    
        /// <summary>
        /// 关联id
        /// </summary>
        public string operator_id { get; set; }
    }
}
