//-----------------------------------------------------------------------
// <copyright file=" yz_operator_freight.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_operator_freight.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_operator_freight Entity Model
    /// </summary>    
export class yz_operator_freight
{
        /// <summary>
        /// 
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 经营范围
        /// </summary>
    public business_scope:string;
    
        /// <summary>
        /// 经营区域
        /// </summary>
    public business_asea:string;
    
        /// <summary>
        /// 水系
        /// </summary>
    public river_system:string;
    
        /// <summary>
        /// 运输船舶种类
        /// </summary>
    public ship_type:string;
    
        /// <summary>
        /// 关联id
        /// </summary>
    public operator_id:string;
}

