//-----------------------------------------------------------------------
// <copyright file=" yz_ship_yearcheck.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_ship_yearcheck.cs
// * history : Created by T4 03/26/2018 22:24:20 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Common.Object;
using System.ComponentModel.DataAnnotations.Schema;

namespace HydrometeorologyGISPluginLib.Data
{
    /// <summary>
    /// yz_ship_yearcheck Entity Model
    /// </summary>    
    [Table("yz_ship_yearcheck")]
    public class yz_ship_yearcheck : ObservableObject
    {
        private string _id;
        /// <summary>
        /// 主键
        /// </summary>        
        public string id
        {
            get { return _id; }
            set { updateProper(ref _id, value);}
        }
    
        private string _bpm_status;
        /// <summary>
        /// 流程状态
        /// </summary>
        public string bpm_status
        {
            get { return _bpm_status; }
            set { updateProper(ref _bpm_status, value);}
        }
    
        private string _create_name;
        /// <summary>
        /// 创建人名称
        /// </summary>
        public string create_name
        {
            get { return _create_name; }
            set { updateProper(ref _create_name, value);}
        }
    
        private string _create_by;
        /// <summary>
        /// 创建人登录名称
        /// </summary>
        public string create_by
        {
            get { return _create_by; }
            set { updateProper(ref _create_by, value);}
        }
    
        private string _update_name;
        /// <summary>
        /// 更新人名称
        /// </summary>
        public string update_name
        {
            get { return _update_name; }
            set { updateProper(ref _update_name, value);}
        }
    
        private string _update_by;
        /// <summary>
        /// 更新人登录名称
        /// </summary>
        public string update_by
        {
            get { return _update_by; }
            set { updateProper(ref _update_by, value);}
        }
    
        private string _sys_org_code;
        /// <summary>
        /// 所属部门
        /// </summary>
        public string sys_org_code
        {
            get { return _sys_org_code; }
            set { updateProper(ref _sys_org_code, value);}
        }
    
        private string _sys_company_code;
        /// <summary>
        /// 所属公司
        /// </summary>
        public string sys_company_code
        {
            get { return _sys_company_code; }
            set { updateProper(ref _sys_company_code, value);}
        }
    
        private DateTime? _create_date;
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? create_date
        {
            get { return _create_date; }
            set { updateProper(ref _create_date, value);}
        }
    
        private DateTime? _update_date;
        /// <summary>
        /// 更新日期
        /// </summary>
        public DateTime? update_date
        {
            get { return _update_date; }
            set { updateProper(ref _update_date, value);}
        }
    
        private string _check_number;
        /// <summary>
        /// 编号
        /// </summary>
        public string check_number
        {
            get { return _check_number; }
            set { updateProper(ref _check_number, value);}
        }
    
        private string _ship_name;
        /// <summary>
        /// 船名
        /// </summary>
        public string ship_name
        {
            get { return _ship_name; }
            set { updateProper(ref _ship_name, value);}
        }
    
        private string _certificate_number;
        /// <summary>
        /// 营业运输证编号
        /// </summary>
        public string certificate_number
        {
            get { return _certificate_number; }
            set { updateProper(ref _certificate_number, value);}
        }
    
        private DateTime? _check_date;
        /// <summary>
        /// 年审日期
        /// </summary>
        public DateTime? check_date
        {
            get { return _check_date; }
            set { updateProper(ref _check_date, value);}
        }
    
        private DateTime? _validity_to;
        /// <summary>
        /// 有效期至
        /// </summary>
        public DateTime? validity_to
        {
            get { return _validity_to; }
            set { updateProper(ref _validity_to, value);}
        }
    
        private string _check_result;
        /// <summary>
        /// 年审结果
        /// </summary>
        public string check_result
        {
            get { return _check_result; }
            set { updateProper(ref _check_result, value);}
        }
    
        private string _check_organ;
        /// <summary>
        /// 审验机关
        /// </summary>
        public string check_organ
        {
            get { return _check_organ; }
            set { updateProper(ref _check_organ, value);}
        }
    
        private DateTime? _issure_date;
        /// <summary>
        /// 发证日期
        /// </summary>
        public DateTime? issure_date
        {
            get { return _issure_date; }
            set { updateProper(ref _issure_date, value);}
        }
    
        private string _check_explain;
        /// <summary>
        /// 年审说明
        /// </summary>
        public string check_explain
        {
            get { return _check_explain; }
            set { updateProper(ref _check_explain, value);}
        }
    
        private string _status;
        /// <summary>
        /// 状态
        /// </summary>
        public string status
        {
            get { return _status; }
            set { updateProper(ref _status, value);}
        }
    
        private string _ship_id;
        /// <summary>
        /// 
        /// </summary>
        public string ship_id
        {
            get { return _ship_id; }
            set { updateProper(ref _ship_id, value);}
        }
    }
}
