//-----------------------------------------------------------------------
// <copyright file=" yz_ship_info.cs" company="xxxx Enterprises">
// * Copyright (C) 2018 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: yz_ship_info.cs
// * history : Created by T4 03/22/2018 16:33:01 
// </copyright>
//-----------------------------------------------------------------------




    /// <summary>
    /// yz_ship_info Entity Model
    /// </summary>    
export class yz_ship_info
{
        /// <summary>
        /// 主键
        /// </summary>
    public id:string;
    
        /// <summary>
        /// 创建人名称
        /// </summary>
    public create_name:string;
    
        /// <summary>
        /// 创建人登录名称
        /// </summary>
    public create_by:string;
    
        /// <summary>
        /// 创建日期
        /// </summary>
    public create_date:Date;
    
        /// <summary>
        /// 更新人名称
        /// </summary>
    public update_name:string;
    
        /// <summary>
        /// 更新人登录名称
        /// </summary>
    public update_by:string;
    
        /// <summary>
        /// 更新日期
        /// </summary>
    public update_date:Date;
    
        /// <summary>
        /// 所属部门
        /// </summary>
    public sys_org_code:string;
    
        /// <summary>
        /// 所属公司
        /// </summary>
    public sys_company_code:string;
    
        /// <summary>
        /// 流程状态
        /// </summary>
    public bpm_status:string;
    
        /// <summary>
        /// 申请原因
        /// </summary>
    public apply_reason:string;
    
        /// <summary>
        /// 申请类型
        /// </summary>
    public apply_type:string;
    
        /// <summary>
        /// 船舶中文名称
        /// </summary>
    public chinese_name:string;
    
        /// <summary>
        /// 船舶英文名称
        /// </summary>
    public english_name:string;
    
        /// <summary>
        /// 沿海内河
        /// </summary>
    public scope:string;
    
        /// <summary>
        /// 运输主水系类型
        /// </summary>
    public river_system:string;
    
        /// <summary>
        /// 运输区域
        /// </summary>
    public area:string;
    
        /// <summary>
        /// 运输类型
        /// </summary>
    public transport_type:string;
    
        /// <summary>
        /// 是否集装箱班轮运输
        /// </summary>
    public has_container:string;
    
        /// <summary>
        /// 本船经营范围是否过闸
        /// </summary>
    public has_sluice:string;
    
        /// <summary>
        /// 曾用名
        /// </summary>
    public used_name:string;
    
        /// <summary>
        /// 船籍港
        /// </summary>
    public registry:string;
    
        /// <summary>
        /// 船舶初始登记号
        /// </summary>
    public first_registration_no:string;
    
        /// <summary>
        /// 船舶登记号
        /// </summary>
    public registration_no:string;
    
        /// <summary>
        /// 船检登记号
        /// </summary>
    public check_registration_no:string;
    
        /// <summary>
        /// 船舶识别号
        /// </summary>
    public check_num:string;
    
        /// <summary>
        /// 运力批文
        /// </summary>
    public approval_no:string;
    
        /// <summary>
        /// 船舶经营人id
        /// </summary>
    public operator_id:string;
    
        /// <summary>
        /// 经营人许可证号码
        /// </summary>
    public operator_license_no:string;
    
        /// <summary>
        /// 船舶所有人
        /// </summary>
    public owner:string;
    
        /// <summary>
        /// 所占船舶股份
        /// </summary>
    public ratio:string;
    
        /// <summary>
        /// 船舶管理人id
        /// </summary>
    public manager_id:string;
    
        /// <summary>
        /// 管理人许可证号码
        /// </summary>
    public manager_license_no:string;
    
        /// <summary>
        /// 船舶类型
        /// </summary>
    public ship_type:string;
    
        /// <summary>
        /// 船体材料
        /// </summary>
    public hull_material:string;
    
        /// <summary>
        /// 船舶总吨
        /// </summary>
    public total_ton:string;
    
        /// <summary>
        /// 净吨位
        /// </summary>
    public suttle_ton:string;
    
        /// <summary>
        /// 建成日期
        /// </summary>
    public build_date:Date;
    
        /// <summary>
        /// 改建日期
        /// </summary>
    public remould_date:Date;
    
        /// <summary>
        /// 主机台数
        /// </summary>
    public mainframe_total_num:string;
    
        /// <summary>
        /// 主机功率
        /// </summary>
    public mainframe_total_power:string;
    
        /// <summary>
        /// 参考载货量
        /// </summary>
    public reference_capacity:string;
    
        /// <summary>
        /// 载箱量
        /// </summary>
    public containe_capacity:string;
    
        /// <summary>
        /// 载车量
        /// </summary>
    public vehicle_capacity:string;
    
        /// <summary>
        /// 载气量
        /// </summary>
    public gas_capacity:string;
    
        /// <summary>
        /// 载客定额
        /// </summary>
    public passenger_capacity:string;
    
        /// <summary>
        /// 船舶来历
        /// </summary>
    public ship_source:string;
    
        /// <summary>
        /// 总长
        /// </summary>
    public total_length:string;
    
        /// <summary>
        /// 船长
        /// </summary>
    public ship_length:string;
    
        /// <summary>
        /// 船宽
        /// </summary>
    public molded_width:string;
    
        /// <summary>
        /// 型深
        /// </summary>
    public molded_depth:string;
    
        /// <summary>
        /// 载重吨
        /// </summary>
    public load_ton:string;
    
        /// <summary>
        /// 是否符合内河尺寸标准
        /// </summary>
    public has_riverboat_norm:string;
    
        /// <summary>
        /// 本船核定的经营范围
        /// </summary>
    public check_scope:string;
    
        /// <summary>
        /// 船舶营运证
        /// </summary>
    public ship_cet_no:string;
    
        /// <summary>
        /// 船舶状态
        /// </summary>
    public status:string;
    
        /// <summary>
        /// 最近年审年份
        /// </summary>
    public check_time:string;
    
        /// <summary>
        /// 船舶经营人
        /// </summary>
    public operator_name:string;
    
        /// <summary>
        /// 船舶管理人
        /// </summary>
    public manager_name:string;
    
        /// <summary>
        /// 船舶营运证到期时间
        /// </summary>
    public expire_time:Date;
}

